/**
 * Pipeline-added coastal species (CA + Pacific NW coast). Researched the same
 * way as the curated seed set and merged into OCEAN_CATALOG via
 * lib/ocean-catalog.ts. All marked autoCompiled → "verify before foraging".
 * Includes closed/protected species (red abalone, sea palm, chitons in CA)
 * catalogued for identification with the closure stated in `regulations`.
 */
import type { OceanSpecies } from "../../ocean-types";
import type { Verification } from "../../species-types";

type RawOcean = Omit<OceanSpecies, "verification" | "autoCompiled"> & {
  verification: Omit<Verification, "lastVerified">;
};

const LAST_VERIFIED = "2026-07-05";

const SEED: RawOcean[] = [
  {
    id: "red-abalone",
    commonNames: ["Red Abalone"],
    scientific: "Haliotis rufescens",
    group: "gastropod",
    habitat: "Rocky reefs and kelp forests from the low intertidal to deep subtidal (most common 6-40 m); grazes on drift and attached kelp.",
    tidalZone: "low",
    regionsPNW: ["California", "Bay Area", "North Coast", "Mendocino", "Redwood Coast", "Oregon", "British Columbia"],
    harvestMonths: [],
    peakMonths: [],
    seasonCue: { tempSensitive: true, notes: "Population collapse tied to marine heatwaves and kelp-forest loss drove the closure; there is currently no open recreational season in California." },
    bestTide: null,
    edibleParts: ["meat"],
    edibility: "edible-with-caution",
    preparation: "Traditionally the muscular foot is shucked, trimmed, sliced thin, pounded to tenderize, then flash-cooked. Note: in California this may only be sourced from farmed or lawful out-of-state supply — wild take is prohibited.",
    cautions: "DO NOT HARVEST. Taking or possessing any abalone in California is illegal — the recreational red abalone fishery has been CLOSED since April 1, 2018 (moratorium), currently extended to at least April 1, 2036. Included here for identification only. Never eat the viscera (gut). Do not confuse with the critically endangered, federally protected black abalone (also illegal to take).",
    biotoxinNotes: "Abalone is a kelp-grazing herbivore, so the foot muscle is comparatively low-risk, but the viscera (gut) can concentrate domoic acid and PSP toxins — never eat the gut. Biotoxins are heat-stable and not destroyed by cooking. Largely moot in California because take is closed; where legal elsewhere, heed PSP/domoic-acid advisories.",
    regulations: "CLOSED. All take and possession of abalone in California is prohibited (14 CCR sec. 29.15). The recreational red abalone fishery has been closed since April 1, 2018 and successive extensions keep it closed until at least April 1, 2036. No license or permit authorizes taking abalone. Managed by CDFW; report poaching to CalTIP 1-888-334-2258.",
    identification: {
      form: "Single large ear-shaped (auriform) shell covering a big muscular foot",
      color: "Brick-red to pink exterior, often encrusted; iridescent pearly interior",
      texture: "Rough, frequently epiphyte-covered exterior; nacreous interior",
      size: "Largest abalone in the world; shell to ~12 in (31 cm), commonly 6-10 in",
      shell: "Ear-shaped with 3-4 raised, open respiratory pores along the margin; thick red band at the shell edge",
      keyFeatures: ["3-4 open, externally raised respiratory pores", "Brick-red exterior, iridescent interior", "Single large muscular foot grips rock", "Largest abalone species, to 12 in"],
    },
    lookalikes: [
      { name: "Black abalone", scientific: "Haliotis cracherodii", danger: "inedible", distinguishingFeature: "Critically endangered and federally protected — illegal to take; smooth dark shell with 5-9 round holes flush to the surface (red abalone has 3-4 raised holes and a red shell).", keyFeatures: ["Smooth dark blue-black shell", "5-9 round, flush respiratory holes", "Federally endangered — never take"] },
      { name: "Flat abalone", scientific: "Haliotis walallensis", danger: "inedible", distinguishingFeature: "Small, flattened, narrow shell (2-5 in) with dark brick-red plus greenish-blue mottling; recreational abalone take is closed regardless.", keyFeatures: ["Flattened, narrow oval shell", "Small (2-5 in)", "All abalone take is closed in CA"] },
    ],
    culinary: { flavor: "Rich, sweet, mildly briny; a prized delicacy", uses: "Tenderized and quickly seared as steaks, or sliced thin for sashimi (from legal farmed sources only)", preservation: "Best fresh; can be frozen" },
    conservationNotes: "Populations collapsed after prolonged ocean warming/marine heatwaves killed the kelp forests abalone feed on, compounded by exploding purple urchin numbers. Slow-growing and slow to recover; the moratorium exists to protect the remaining stock.",
    sources: [
      { name: "CDFW News - red abalone recreational fishery closure extended", url: "https://wildlife.ca.gov/News/Archive/california-fish-and-game-commission-extends-red-abalone-recreational-fishery-closure-finds-cesa-listing-of-bear-lake-buckwheat-warranted" },
      { name: "CDFW Ocean Sport Fishing - Invertebrate Regulations", url: "https://wildlife.ca.gov/Fishing/Ocean/Regulations/Sport-Fishing/Invertebrate-Fishing-Regs" },
      { name: "UCSC Multi-Agency Rocky Intertidal Network - Haliotis rufescens", url: "https://marine.ucsc.edu/target/haliotis-rufescens/" },
    ],
    verification: { sourcesAgreeing: 3, consensus: "strong", disputeNotes: "The exact closure end date has moved with successive extensions (earlier ones ran to 2021 and 2026); the most recent action extends it to April 1, 2036. Confirm the current end date with CDFW." },
  },
  {
    id: "pacific-geoduck",
    commonNames: ["Pacific Geoduck", "Geoduck", "King Clam"],
    scientific: "Panopea generosa",
    group: "bivalve",
    habitat: "Buried 2-3 ft deep in mud, sand, or gravel of protected inland waters (Puget Sound, Hood Canal); from the low intertidal to 360+ ft subtidal.",
    tidalZone: "low",
    regionsPNW: ["Washington", "Puget Sound", "Olympic", "British Columbia"],
    harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    peakMonths: [5, 6, 7],
    seasonCue: { tempSensitive: true, notes: "Recreational intertidal access hinges on extreme minus tides (only exposed at -2.0 ft or lower, roughly 20 tides a year, mostly late-spring/summer daytime lows). PSP/biotoxin risk rises with warm-water blooms, so check advisories." },
    bestTide: "Extreme minus tides, -2.0 ft or lower",
    edibleParts: ["siphon", "meat"],
    edibility: "edible-with-caution",
    preparation: "Blanch the siphon 10-15 seconds, plunge into an ice bath, then peel the skin off like a glove; slice thin for raw preparations. Clean the body/mantle meat and cook it; remove viscera.",
    cautions: "Harvest is physically demanding and limited to a handful of extreme minus tides per year. Take only your one clam, refill all holes, and never keep just the siphon (illegal). Confirm the specific beach is open for both season and biotoxin before eating — geoduck can carry PSP. Do not confuse with horse/gaper clams, which have different limits.",
    biotoxinNotes: "Filter feeder that can accumulate PSP (saxitoxin) and domoic acid (ASP). Neither cooking nor freezing destroys these toxins. Always confirm the exact beach is open on the WA Department of Health Shellfish Safety Map or via the biotoxin hotline before harvesting or eating.",
    regulations: "Washington: a shellfish or combination license is required. Daily limit is the FIRST ONE geoduck dug per person, kept regardless of size, quality, or condition. Hand tools only; refill holes immediately; injuring the siphon or possessing only the siphon is illegal. Seasons are beach-specific — check WDFW shellfish beaches and the WA DOH Shellfish Safety Map. WA DOH biotoxin hotline 1-800-562-5632.",
    identification: {
      form: "Enormous burrowing clam with a permanently protruding siphon/neck",
      color: "Creamy-white shell with thin brown patches; tan-brown siphon skin",
      texture: "Firm, crunchy siphon meat; softer body/mantle meat",
      size: "Shell ~6-8 in; siphon extends well beyond the shell; avg ~2 lb, verified to 8+ lb; can live 168 years",
      shell: "White, oblong, gaping shell with concentric rings — too small to contain the huge siphon and mantle",
      keyFeatures: ["Massive siphon/'neck' cannot retract into the gaping shell", "World's largest burrowing clam", "Buried 2-3 ft deep", "Only exposed on extreme minus tides"],
    },
    lookalikes: [
      { name: "Horse clam / gaper clam", scientific: "Tresus capax / Tresus nuttallii", danger: "edible-with-caution", distinguishingFeature: "Also large with a big siphon, but the siphon tip bears two hardened leathery plates and the clam is shallower; different bag limits apply and they also carry PSP.", keyFeatures: ["Two leathery plates at siphon tip", "Shallower burrow than geoduck", "Different daily limit"] },
    ],
    culinary: { flavor: "Sweet, briny, clean; crisp crunchy siphon", uses: "Siphon raw as sashimi/crudo or ceviche; body meat cooked in chowder, stir-fry, or fritters", preservation: "Best fresh; freezes acceptably" },
    conservationNotes: "Extremely long-lived (up to 168 years) and slow to replace: harvested beds take about 55 years on average to return to pre-harvest densities. A WDFW Priority Species — dig responsibly, refill holes, respect the one-per-day limit.",
    sources: [
      { name: "WDFW - Geoduck clam (Panopea generosa) species page", url: "https://wdfw.wa.gov/species-habitats/species/panopea-generosa" },
      { name: "WA Dept. of Health - Marine Biotoxins / Shellfish Safety", url: "https://doh.wa.gov/community-and-environment/shellfish/recreational-shellfish/illnesses/biotoxins" },
      { name: "NOAA Fisheries - Geoduck", url: "https://www.fisheries.noaa.gov/species/geoduck" },
    ],
    verification: { sourcesAgreeing: 3, consensus: "strong", disputeNotes: "Beach-specific seasons and biotoxin closures change frequently and must be checked each trip. The older synonym Panopea abrupta appears in some literature." },
  },
  {
    id: "nuttalls-cockle",
    commonNames: ["Nuttall's Cockle", "Basket Cockle", "Heart Cockle"],
    scientific: "Clinocardium nuttallii",
    group: "bivalve",
    habitat: "Shallow-buried (only a few inches) in sand-gravel of sheltered bays, estuaries, and eelgrass flats; low intertidal to shallow subtidal.",
    tidalZone: "low",
    regionsPNW: ["California", "North Coast", "Oregon", "Washington", "Olympic", "Puget Sound", "British Columbia"],
    harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    peakMonths: [4, 5, 6],
    seasonCue: { tempSensitive: true, notes: "Available year-round at low tides. PSP and domoic-acid blooms peak in warmer water, so biotoxin risk is higher late spring through fall — check advisories before harvest." },
    bestTide: "Low to minus tides",
    edibleParts: ["meat"],
    edibility: "edible-with-caution",
    preparation: "Purge in clean seawater, then steam open or shuck; chop the meat for chowder or pasta. Its strong flavor suits cooked dishes.",
    cautions: "Confirm biotoxin status before eating — cockles filter-feed and can carry PSP and domoic acid. Observe state size and bag limits and beach-specific seasons; purge sand thoroughly before cooking.",
    biotoxinNotes: "Filter feeder subject to PSP (saxitoxin) and domoic acid (ASP). Toxins are heat-stable — cooking does not remove them. Check current state biotoxin advisories/closures (WA DOH, OR ODA, CA CDPH) before harvesting.",
    regulations: "A shellfish/sport license is required. Washington: 2.5 in minimum size, counted within the combined 40-clam / 10-lb daily clam limit. Oregon: part of the 20 bay-clam daily limit (ODFW; biotoxin by ODA, hotline 1-800-448-2474). California: no clam/cockle-specific closed season, size, or bag limit, but general invertebrate rules and CDPH advisories apply. Beach-specific seasons and biotoxin closures apply everywhere.",
    identification: {
      form: "Plump, near-globular ribbed bivalve",
      color: "Yellowish-tan with brown or reddish accents",
      texture: "Strongly ribbed and ridged",
      size: "Shell to ~4-5.5 in across; commonly 3-4 in",
      shell: "Thick, rounded/heart-shaped shell with 34-38 strong radiating ribs crossed by fine concentric growth rings",
      keyFeatures: ["34-38 strong radiating ribs", "Plump, heart-shaped shell", "Short siphon; shallow burrower a few inches down", "Yellowish-tan shell with brown accents"],
    },
    lookalikes: [
      { name: "Butter clam", scientific: "Saxidomus gigantea", danger: "edible-with-caution", distinguishingFeature: "Co-occurs in the same bays but has a smooth oval shell with concentric rings only (no radiating ribs) and retains PSP far longer — subject to separate, longer closures.", keyFeatures: ["Smooth shell, concentric rings only", "No radiating ribs", "Deeper burrower; higher PSP risk"] },
      { name: "Native littleneck clam", scientific: "Leukoma staminea", danger: "edible-with-caution", distinguishingFeature: "Smaller, with both radiating and concentric lines forming a cross-hatched pattern rather than the cockle's coarse ribs.", keyFeatures: ["Cross-hatched sculpture", "Smaller, rounder", "Shallow burrower"] },
    ],
    culinary: { flavor: "Strong, briny clam flavor", uses: "Chowders, pasta, and steamed dishes; the robust flavor favors cooked preparations", preservation: "Best fresh; can be steamed and the meat frozen" },
    conservationNotes: "A culturally important food for Indigenous peoples of the Pacific Northwest coast. Populations in small bays can be depleted by heavy digging, so observe limits and refill holes.",
    sources: [
      { name: "WDFW - Basket cockle (Clinocardium nuttallii) species page", url: "https://wdfw.wa.gov/species-habitats/species/clinocardium-nuttallii" },
      { name: "ODFW - Oregon shellfish regulations", url: "https://myodfw.com/articles/oregon-shellfish-regulations" },
      { name: "ODA - Recreational Shellfish Biotoxin Closures", url: "https://www.oregon.gov/oda/food-safety/shellfish/pages/shellfish-closures.aspx" },
    ],
    verification: { sourcesAgreeing: 3, consensus: "strong", disputeNotes: "Maximum shell size is reported variously from ~4 to 5.5 in. State-specific limits, seasons, and biotoxin closures should be reconfirmed each year." },
  },
  {
    id: "butter-clam",
    commonNames: ["Butter Clam", "Washington Clam", "Smooth Washington Clam"],
    scientific: "Saxidomus gigantea",
    group: "bivalve",
    habitat: "Burrows up to ~18 in deep in sand, gravel, or cobble of protected beaches and bays; mid-intertidal to subtidal.",
    tidalZone: "mid",
    regionsPNW: ["California", "Oregon", "Washington", "Olympic", "Puget Sound", "British Columbia"],
    harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    peakMonths: [11, 12, 1, 2],
    seasonCue: { tempSensitive: true, notes: "Because butter clams retain PSP for a year or more, the calendar matters less than the current, beach-specific biotoxin certification — cooler months are generally lower-risk, but always verify the specific beach is open for butter clams." },
    bestTide: "Low to minus tides",
    edibleParts: ["meat"],
    edibility: "edible-with-caution",
    preparation: "Only where the beach is certified safe for butter clams: steam open or shuck. Many harvesters remove the black-tipped siphon, which reduces but does NOT reliably eliminate PSP toxin. Cooking does not detoxify PSP.",
    cautions: "Highest biotoxin concern of these clams. Butter clams concentrate PSP and RETAIN it for months to years, and are FREQUENTLY placed under their own separate, longer closure even when other clamming is open. Removing the siphon is not a reliable safeguard. Only eat butter clams from a beach specifically certified open for them; check the state biotoxin map/hotline every single time — when in doubt, do not eat.",
    biotoxinNotes: "HIGH-RISK for PSP. Butter clams accumulate saxitoxin and retain it far longer than most clams — up to a year or more — often concentrated in the black-tipped siphon. Cooking and freezing do NOT remove it, and toxin distribution within the clam is variable, so siphon removal is unreliable. Illnesses have been documented a year after a bloom ended. Also subject to domoic acid. Harvest only where the specific beach is certified open for butter clams.",
    regulations: "A license is required. Washington: 1.5 in minimum size, counted within the combined 40-clam / 10-lb daily clam limit; butter (and varnish) clams are frequently under separate, longer biotoxin closures than other species. Oregon: part of the 20 bay-clam daily limit. Always check biotoxin status before harvest: WA DOH 1-800-562-5632; OR ODA 1-800-448-2474; CA CDPH 1-800-553-4133.",
    identification: {
      form: "Oval, thick-shelled, deep-burrowing bivalve",
      color: "White to grey or yellow; blue or pink staining may be present",
      texture: "Chalky shell with fine concentric ridges",
      size: "Shell up to ~5 in; commonly 3-4 in",
      shell: "Oval, thick, chalky shell with concentric rings only and no radiating lines; siphon tipped with black",
      keyFeatures: ["Concentric rings only, no radiating ribs", "Thick chalky oval shell", "Black-tipped siphon", "Deep burrower (to ~18 in)"],
    },
    lookalikes: [
      { name: "Varnish clam", scientific: "Nuttallia obscurata", danger: "edible-with-caution", distinguishingFeature: "Also retains PSP and is closed under the same butter-clam biotoxin closures; distinguished by a shiny brown varnish-like periostracum and purple-tinged interior.", keyFeatures: ["Glossy brown 'varnished' shell", "Purple interior staining", "Same PSP closures as butter clam"] },
      { name: "Native littleneck clam", scientific: "Leukoma staminea", danger: "edible-with-caution", distinguishingFeature: "Smaller and rounder with cross-hatched sculpture (both radiating and concentric lines); a shallower burrower that clears PSP faster.", keyFeatures: ["Cross-hatched shell sculpture", "Smaller, rounder", "Shallow burrower"] },
    ],
    culinary: { flavor: "Sweet and rich — the source of its 'butter' name", uses: "Steamed, in chowder, or as fritters — only where certified PSP-safe", preservation: "Best fresh" },
    conservationNotes: "Generally abundant; the dominant concern is biotoxin safety rather than conservation. Refill holes after digging.",
    sources: [
      { name: "WDFW - Butter clam (Saxidomus gigantea) species page", url: "https://wdfw.wa.gov/species-habitats/species/saxidomus-gigantea" },
      { name: "WA Dept. of Health - Island County butter/varnish clam closure", url: "https://doh.wa.gov/newsroom/most-island-county-remains-closed-butter-and-varnish-clam-harvesting" },
      { name: "Harding et al. - PSP in butter clams; siphon-cleaning reliability (NCBI/PMC)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12197486/" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "The reliability of siphon removal is disputed: regulators historically recommended it, but research shows variable toxin distribution makes it unreliable. Treat butter clams as unsafe unless the specific beach is certified open." },
  },
  {
    id: "black-turban-snail",
    commonNames: ["Black Turban Snail", "Black Tegula", "Black Turban"],
    scientific: "Tegula funebralis",
    group: "gastropod",
    habitat: "Rocky intertidal (upper-to-mid zone); grazes algae on rock surfaces and in tidepools.",
    tidalZone: "mid",
    regionsPNW: ["California", "Bay Area", "North Coast", "Mendocino", "Redwood Coast", "Oregon", "Washington", "Olympic", "British Columbia"],
    harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    peakMonths: [1, 2, 3, 11, 12],
    seasonCue: { tempSensitive: true, notes: "Harvestable year-round at low tide on rocky shores; biotoxin blooms are warm-water driven, so cooler months are generally lower-risk — still check advisories." },
    bestTide: "Low tide on rocky shores",
    edibleParts: ["meat"],
    edibility: "edible-cooked",
    preparation: "Purge in clean seawater for 1-2 days, boil about 5-10 minutes, then pick the meat from the shell with a pin; discard the operculum and the gritty gut coil. Serve like periwinkles or escargot, e.g. in garlic butter.",
    cautions: "Purge and cook thoroughly — unpurged snails taste of gut grit and trapped sand. Biotoxin risk is lower than in filter-feeding clams but not zero; check PSP/domoic-acid advisories. Avoid over-harvesting (this species was historically depleted), leave small snails, and respect MPA/reserve no-take zones.",
    biotoxinNotes: "As an algae grazer, PSP risk is lower than in filter-feeding clams, but herbivorous gastropods can still bioaccumulate saxitoxin from toxic microalgae and biofilms, and biotoxins are not removed by cooking. Purge and clean well and observe local PSP and domoic-acid advisories (CA CDPH 1-800-553-4133).",
    regulations: "A California sport fishing license is required (age 16+). No species-specific size limit; turban/marine snails fall under the general invertebrate daily bag limit (35) — confirm the current number in CDFW's Ocean Sport Fishing Regulations. Subject to tidepool/intertidal invertebrate rules; many MPAs, reserves, and refuges prohibit take.",
    identification: {
      form: "Rounded turban-shaped marine snail",
      color: "Black to dark purplish-grey; often worn to pearly white at the apex",
      texture: "Smooth, frequently eroded shell surface",
      size: "Shell 20-50 mm (up to ~2 in) in diameter",
      shell: "Low-spired thick turban shell; blackish exterior, pearly interior, rounded aperture with a pearly lip",
      keyFeatures: ["Black/dark turban-shaped shell", "Pearly interior and worn white apex", "Rounded aperture with pearly lip", "Grazes rocky mid-intertidal in groups"],
    },
    lookalikes: [
      { name: "Brown turban snail", scientific: "Tegula brunnea", danger: "edible", distinguishingFeature: "Same genus and also edible, but shell is chestnut/tan-brown rather than black and it tends to sit lower in the intertidal.", keyFeatures: ["Chestnut-brown shell", "Lower intertidal/subtidal edge", "Also edible"] },
    ],
    culinary: { flavor: "Mild and briny, similar to periwinkle or escargot", uses: "Purged, boiled, and picked from the shell like periwinkles/escargot; served in garlic butter or salads", preservation: "Best cooked fresh" },
    conservationNotes: "Heavily over-harvested for food in the early 1900s, causing sharp population declines; still gathered today. Harvest modestly, take only larger snails, and leave enough to sustain local rocky-shore populations.",
    sources: [
      { name: "CDFW Ocean Sport Fishing - Invertebrate Regulations", url: "https://wildlife.ca.gov/Fishing/Ocean/Regulations/Sport-Fishing/Invertebrate-Fishing-Regs" },
      { name: "Wikipedia - Tegula funebralis", url: "https://en.wikipedia.org/wiki/Tegula_funebralis" },
      { name: "Non-Traditional Vectors for Paralytic Shellfish Poisoning (gastropod PSP) - PMC", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2525492/" },
    ],
    verification: { sourcesAgreeing: 3, consensus: "strong", disputeNotes: "PSP risk for herbivorous gastropods is lower and less studied than for filter feeders, but documented gastropod PSP cases exist, so advisories still apply. Also cited under the synonym Chlorostoma funebralis." },
  },
  {
    id: "black-katy-chiton",
    commonNames: ["Black Katy Chiton", "Black Leather Chiton", "Black Chiton"],
    scientific: "Katharina tunicata",
    group: "gastropod",
    habitat: "Wave-swept, exposed rocky shores; clings tightly to bare rock and boulders in the surf zone. An algae grazer of open-coast headlands rather than sheltered bays.",
    tidalZone: "mid",
    regionsPNW: ["California", "North Coast", "Mendocino", "Redwood Coast", "Oregon", "Washington", "Olympic", "British Columbia"],
    harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    peakMonths: [4, 5, 6],
    seasonCue: { tempSensitive: false, notes: "Available year-round on exposed rock in Washington/Oregon/BC where legal; traditionally gathered at spring and early-summer minus tides. NOT legal to collect in California." },
    bestTide: "Low or minus tides (0.0 ft or lower) that expose mid-intertidal wave-swept rock",
    edibleParts: ["meat"],
    edibility: "edible-cooked",
    preparation: "Only the large muscular foot is eaten. Pry the animal off the rock, remove the eight plates and dark girdle, and separate the orange-yellow foot from the viscera. The meat is very tough: traditionally tenderized by pounding, then eaten raw, boiled, steamed, or roasted over coals; also chopped into chowder. Overcooking makes it rubbery.",
    cautions: "ILLEGAL to collect in California — CDFW prohibits taking chitons from the rocky intertidal (grouped with abalone, sea stars, and barnacles as no-take). Harvest only in Washington, Oregon, or BC where permitted, and never inside marine reserves/protected areas. As a rock-clinging grazer it can dislodge whole populations if over-collected. Clean thoroughly; discard gut.",
    biotoxinNotes: "Lower biotoxin risk than filter-feeding bivalves because it is an algal grazer, not a filter feeder, but not risk-free — heed all local PSP/domoic-acid closures, since grazers can still accumulate toxins from toxic algae. Check the state shellfish-safety hotline before eating.",
    regulations: "California: recreational take of chitons is PROHIBITED (CDFW rules protecting rocky-intertidal invertebrates); a no-take species statewide for sport harvest. Washington: an 'unclassified marine invertebrate' — a valid shellfish/combined license and general daily limits apply. Oregon: allowed with a shellfishing license under general invertebrate rules; no take in marine reserves/gardens. All: no take in MPAs; ages 16+ need a license.",
    identification: {
      form: "Oval, football-shaped body with eight overlapping shell plates set in a broad girdle",
      color: "Shiny jet-black leathery girdle; whitish/gray plates; underside foot dull orange to yellow",
      texture: "Smooth, leathery, rubbery girdle; clamps hard to rock",
      size: "Average ~7 cm, up to 12 cm long",
      shell: "Eight butterfly-shaped plates mostly overgrown by the black girdle, leaving a diamond pattern of exposed white plate down the midline",
      keyFeatures: ["Glossy black girdle almost covering the plates (only a central diamond strip of white shows)", "Bright orange-yellow foot underneath", "On wave-exposed bare rock at mid-intertidal", "Firmly cemented; hard to pry off"],
    },
    lookalikes: [
      { name: "Gumboot / giant Pacific chiton", scientific: "Cryptochiton stelleri", danger: "edible-with-caution", distinguishingFeature: "Much larger (to 33 cm), brick-red to brown, with NO plates visible (fully covered by leathery mantle).", keyFeatures: ["Massive brick-red 'meatloaf' body", "No exposed plates", "Foot also edible but very tough and bland"] },
      { name: "Mossy chiton", scientific: "Mopalia muscosa", danger: "edible", distinguishingFeature: "Girdle bears stiff hairs/bristles and does not cover the plates; usually on more sheltered rock.", keyFeatures: ["Hairy/bristly girdle", "Plates fully exposed, dull olive-brown", "Notch at rear of girdle"] },
    ],
    culinary: { flavor: "Briny, shellfish/abalone-like, mild; chewy", uses: "Traditional Northwest Coast food; foot pounded and eaten raw, grilled, or in chowders and soups", preservation: "Traditionally dried or smoked for storage" },
    conservationNotes: "A culturally important Indigenous food for millennia. Slow to recolonize wave-swept rock; California protects it as a no-take rocky-intertidal invertebrate. Take only sparingly where legal and never strip a patch.",
    sources: [
      { name: "CDFW Marine Management News - Tidepool foraging bag limits (chitons no-take)", url: "https://cdfwmarine.wordpress.com/2020/08/20/bag-limits-for-saltwater-snails-following-the-regulations-for-tidepool-foraging/" },
      { name: "Animal Diversity Web - Katharina tunicata", url: "https://animaldiversity.org/accounts/Katharina_tunicata/" },
      { name: "Wikipedia - Katharina tunicata", url: "https://en.wikipedia.org/wiki/Katharina_tunicata" },
    ],
    verification: { sourcesAgreeing: 3, consensus: "strong", disputeNotes: "Edibility and traditional-food use are undisputed. Regulatory status differs sharply by state: California prohibits recreational take of chitons, whereas WA/OR/BC permit it under general shellfish/invertebrate rules." },
  },
  {
    id: "northern-kelp-crab",
    commonNames: ["Northern Kelp Crab", "Shield-backed Kelp Crab", "Kelp Crab"],
    scientific: "Pugettia producta",
    group: "crustacean",
    habitat: "Kelp beds, eelgrass, and floating/attached algae on rocky coast; also very common on pilings, floats, and jetties. Ranges from the low intertidal into the shallow subtidal.",
    tidalZone: "low",
    regionsPNW: ["California", "Bay Area", "North Coast", "Mendocino", "Redwood Coast", "Oregon", "Washington", "Olympic", "Puget Sound", "British Columbia"],
    harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    peakMonths: [10, 11, 12, 1],
    seasonCue: { tempSensitive: false, notes: "Available year-round; hand-caught off kelp and pilings at low tide. Avoid recently molted 'soft-shell' crabs (mostly warmer months) which have little meat and should be released." },
    bestTide: "Low/minus tides that expose kelp beds, pilings, and eelgrass; also caught by dip net near floats",
    edibleParts: ["meat", "legs"],
    edibility: "edible",
    preparation: "Edible but yields little meat; not a prime food crab. Boil or steam whole for 10-15 minutes, then pick body and legs. Best used to enrich stock/bisque given the small meat yield. Handle carefully — the strong claws and hooked legs pinch and grip.",
    cautions: "Not toxic, but low meat yield makes it a marginal food crab. Grips kelp/pilings tightly and pinches hard — grab from behind the carapace. Know your local crab rules and identify before keeping. Release soft (recently molted) individuals.",
    biotoxinNotes: "Crab body ('butter'/viscera) can concentrate domoic acid and PSP toxins during harmful algal blooms; when a region is under a crab biotoxin advisory, discard the viscera and eat only leg/body meat, or avoid. Check state health-department crab advisories.",
    regulations: "California: no species-specific limit — falls under the general 35-per-day marine-invertebrate default; a sport-fishing license is required for anyone 16+; no take in state marine reserves. Washington: a shellfish/combined license and general crab rules apply (it is not Dungeness or red rock crab and is rarely targeted). Take by hand or dip net; no take in protected areas.",
    identification: {
      form: "Smooth, shield- or bell-shaped carapace, widest toward the front, with a sharply pointed two-horned rostrum and long spider-like legs",
      color: "Olive-brown to reddish or khaki, often matching kelp; underside paler",
      texture: "Smooth, almost polished carapace (unlike bumpy rock crabs)",
      size: "Carapace to about 9-10 cm long; legs relatively long",
      shell: "Hard, glossy, nearly spineless carapace with two forward-projecting rostral horns",
      keyFeatures: ["Smooth glossy shield-shaped carapace (no bumps)", "Two pointed horns at the front (rostrum)", "Long grasping legs used to climb kelp", "Often clinging to kelp or pilings"],
    },
    lookalikes: [
      { name: "Graceful (slender) kelp crab", scientific: "Pugettia gracilis", danger: "edible", distinguishingFeature: "Smaller, with more slender legs and more spines/tubercles on the carapace margins.", keyFeatures: ["Smaller than P. producta", "More lateral spines", "Also on kelp/eelgrass"] },
      { name: "Red rock crab", scientific: "Cancer productus", danger: "edible", distinguishingFeature: "Bumpy fan-shaped carapace with toothed front edge and black-tipped claws; far more meat.", keyFeatures: ["Wide toothed carapace edge", "Black-tipped pincers", "Much better eating"] },
    ],
    culinary: { flavor: "Sweet but faint, distinctly kelp/seaweed-tinged", uses: "Occasional catch for stock, bisque, or a light pick; not a mainstay crab", preservation: null },
    conservationNotes: "Abundant and not of conservation concern; an important grazer/prey in kelp forests. Take only what you will use and release small or soft crabs.",
    sources: [
      { name: "WDFW - Northern kelp crab (Pugettia producta)", url: "https://wdfw.wa.gov/species-habitats/species/pugettia-producta" },
      { name: "U.S. Fish & Wildlife Service - Northern Kelp Crab", url: "https://www.fws.gov/species/northern-kelp-crab-pugettia-producta" },
      { name: "Wikipedia - Pugettia producta", url: "https://en.wikipedia.org/wiki/Pugettia_producta" },
    ],
    verification: { sourcesAgreeing: 3, consensus: "strong", disputeNotes: "Edible but low-yield and rarely targeted. No species-specific bag limit in CA or WA; it falls under general invertebrate/crab provisions, so anglers apply the default limits and licensing." },
  },
  {
    id: "softshell-clam",
    commonNames: ["Softshell Clam", "Eastern Softshell Clam", "Steamer Clam", "Longneck Clam"],
    scientific: "Mya arenaria",
    group: "bivalve",
    habitat: "Buries 8-14 inches deep in soft mud and sand of estuaries, bays, and sloughs; an introduced (non-native) Atlantic species well established in West Coast estuaries such as San Francisco Bay, Humboldt Bay, and Pacific Northwest bays.",
    tidalZone: "mid",
    regionsPNW: ["Bay Area", "North Coast", "Oregon", "Washington", "Puget Sound", "British Columbia"],
    harvestMonths: [1, 2, 3, 4, 9, 10, 11, 12],
    peakMonths: [10, 11, 12, 1, 2],
    seasonCue: { tempSensitive: true, notes: "Diggable year-round where beaches are open, but PSP/biotoxin closures are most common in warm months (roughly May-Oct); the traditional 'months with an R' (Sep-Apr) guideline reflects this. ALWAYS confirm the beach is open and biotoxin-free first." },
    bestTide: "Large minus low tides (-1.0 ft or lower) that expose estuarine mudflats; watch for the clam's siphon 'show' or squirt hole",
    edibleParts: ["whole", "siphon", "meat"],
    edibility: "edible-with-caution",
    preparation: "A classic 'steamer' and fried-clam species. Dig with a fork/shovel, purge in seawater to expel grit, then steam open (discard any that stay shut), or shuck for frying/chowder. The long siphon (neck) skin is peeled off; body and neck are both eaten. Cook thoroughly — but cooking does NOT destroy PSP/biotoxins.",
    cautions: "Filter feeder that concentrates PSP toxins and domoic acid — potentially fatal and NOT removed by cooking, freezing, or cleaning. Never harvest without checking the current biotoxin status and beach-closure status for that exact location. Also avoid polluted/urban estuaries (bacteria, sewage, heavy metals). Refill dig holes.",
    biotoxinNotes: "High-priority PSP vector; can also carry domoic acid (ASP) and Vibrio. Biotoxins are invisible, tasteless, and heat-stable. WA DOH Biotoxin Hotline 1-800-562-5632; CA check CDPH shellfish advisory and the annual mussel-quarantine period; OR check ODA/ODFW closures before eating.",
    regulations: "Washington: valid fishing license with shellfish privileges (16+); no minimum size for softshells, but the daily limit counts within the combined clam limit of 40 clams / 10 lb in shell (excludes geoducks and horse clams); seasons are beach-specific — check WDFW and DOH biotoxin closures. California: sport-fishing license required; observe CDFW clam limits and CDPH shellfish quarantines (esp. May 1-Oct 31 mussel quarantine). Oregon: shellfish license and ODFW/ODA rules. As a non-native species there is generally no conservation minimum size.",
    identification: {
      form: "Elongate oval bivalve with a long fused siphon ('neck') that cannot fully retract, so the shell gapes at the rear",
      color: "Chalky white to gray, often stained by mud; siphon tips dark",
      texture: "Thin, brittle, chalky shell with a flaky periostracum; surface uneven",
      size: "To about 15 cm (6 in) long",
      shell: "Thin/brittle, gaping at the siphon end; the left valve has a distinctive spoon-shaped shelf (chondrophore) inside the hinge",
      keyFeatures: ["Thin brittle chalky-white shell that gapes at one end", "Long dark-tipped siphon/neck", "Spoon-shaped chondrophore inside the left valve hinge", "In soft estuarine mud, deep burrow with a squirting show hole"],
    },
    lookalikes: [
      { name: "Pacific gaper / horse clam", scientific: "Tresus capax / Tresus nuttallii", danger: "edible-with-caution", distinguishingFeature: "Much larger and heavier shell; siphon tips bear leathery skin flaps; different bag limits (excluded from the 40-clam limit).", keyFeatures: ["Large heavy shell", "Leathery plates on siphon tip", "Also a PSP vector"] },
      { name: "Purple varnish clam", scientific: "Nuttallia obscurata", danger: "edible-with-caution", distinguishingFeature: "Rounder shell with glossy brown/purple varnish-like periostracum and purple interior.", keyFeatures: ["Shiny brown varnished exterior", "Purple-tinged interior", "Introduced; also a PSP vector"] },
    ],
    culinary: { flavor: "Sweet, briny, tender; classic clam flavor", uses: "Steamers, fried clams/clam strips, chowder, clam fritters", preservation: "Can be shucked and frozen or canned; keep chilled and alive until cooking" },
    conservationNotes: "Non-native (introduced from the Atlantic to San Francisco Bay in the 1870s and now widespread); no conservation concern and harvest can help control it. Refill all dig holes to protect other clam beds and eelgrass.",
    sources: [
      { name: "WDFW - (Eastern) softshell clam (Mya arenaria)", url: "https://wdfw.wa.gov/species-habitats/species/mya-arenaria" },
      { name: "WDFW - Clam, mussel, and oyster harvest (limits & biotoxin safety)", url: "https://wdfw.wa.gov/places-to-go/shellfish-beaches" },
      { name: "Smithsonian NEMESIS - Mya arenaria (introduced range)", url: "https://invasions.si.edu/nemesis/species_summary/-60" },
    ],
    verification: { sourcesAgreeing: 3, consensus: "strong", disputeNotes: "Introduced status, PSP biotoxin risk, and WA's 40-clam/10-lb combined limit are consistent across sources. Exact bag limits and open seasons vary by beach/state and by biotoxin closures, so real-time official checks are required." },
  },
  {
    id: "sea-palm",
    commonNames: ["Sea Palm", "Sea Palm Kelp"],
    scientific: "Postelsia palmaeformis",
    group: "kelp",
    habitat: "Fully exposed, surf-pounded rocky headlands and reefs; grows in dense stands in the mid-intertidal, often rooted among California mussel beds where wave disturbance opens space. An annual brown alga.",
    tidalZone: "mid",
    regionsPNW: ["California", "North Coast", "Mendocino", "Redwood Coast", "Oregon", "Washington", "Olympic", "British Columbia"],
    harvestMonths: [],
    peakMonths: [],
    seasonCue: { tempSensitive: true, notes: "Annual: recruits in spring, matures over summer, senesces by fall; badly hit by marine heatwaves with slow recovery. Harvest timing is moot in California because recreational harvest is ILLEGAL." },
    bestTide: null,
    edibleParts: ["blade", "stipe"],
    edibility: "edible-with-caution",
    preparation: "Where legal (not California), the grooved blades and tender upper stipe are eaten raw, blanched, sautéed, pickled, or dried; flavor is briny and slightly sweet. In California DO NOT harvest — it is protected. Photograph and admire only.",
    cautions: "PROTECTED IN CALIFORNIA — recreational harvest, cutting, or disturbing of sea palm is ILLEGAL statewide under CDFW rules; violations are citable. Oregon prohibits harvest entirely. Only Washington and British Columbia allow limited, licensed harvest. Beyond the law, it grows in dangerous, surf-pounded zones where sneaker waves are a serious drowning hazard.",
    biotoxinNotes: "Seaweeds are not a PSP/biotoxin vector, but where legal to harvest choose clean, unpolluted open-coast water away from runoff, harbors, and outfalls; rinse in clean seawater.",
    regulations: "California: recreational harvest PROHIBITED — CDFW explicitly bans recreational take/disturbance of sea palm (alongside eelgrass and surfgrass). Oregon: harvest of sea palm is prohibited (cannot be cut or disturbed anywhere). Washington and British Columbia: limited harvest allowed only with the appropriate license/permit. No take in any marine reserve or protected area.",
    identification: {
      form: "Miniature palm-tree shape: a single upright, hollow, flexible stipe topped by a crown of many grooved blades",
      color: "Olive-green to golden-brown",
      texture: "Rubbery, flexible stipe that springs back after each wave; grooved strap-like blades",
      size: "Up to ~60 cm tall",
      holdfast: "Small, strong disc-like holdfast gripping bare rock in the surf zone",
      keyFeatures: ["Looks like a tiny palm tree standing upright in crashing surf", "Grows in dense clusters on the most wave-exposed rock", "Hollow springy stipe with a topknot of grooved blades", "Mid-intertidal among mussels"],
    },
    lookalikes: [
      { name: "Bull kelp (juvenile)", scientific: "Nereocystis luetkeana", danger: "edible", distinguishingFeature: "Has a single round gas-filled float (bulb) with blades trailing from it; a subtidal species, not standing upright in surf.", keyFeatures: ["Single round float/bulb", "Long whip-like stipe", "Subtidal, not mid-intertidal surf rock"] },
    ],
    culinary: { flavor: "Briny, mildly sweet, tender", uses: "Where legal only: raw in salads, blanched, sautéed, pickled, or dried as a snack", preservation: "Air-dried where legally harvested (not in California)" },
    conservationNotes: "Protected in California and Oregon due to past over-harvest, patchy distribution, poor dispersal, and steep declines during marine heatwaves. A keystone competitor in wave-swept mussel beds. Treat as look-but-don't-touch on the CA/OR coast.",
    sources: [
      { name: "CDFW - Recreational Harvest of Kelp and Other Marine Algae (sea palm prohibited)", url: "https://wildlife.ca.gov/Conservation/Marine/Kelp/Recreational-Harvest" },
      { name: "MARINe (UC Santa Cruz) - Postelsia palmaeformis", url: "https://marine.ucsc.edu/target/postelsia/" },
      { name: "Oregon SWAP - Sea Palm (Postelsia palmaeformis) overview", url: "https://swap.oregon.gov/media/Sea-Palm.pdf" },
    ],
    verification: { sourcesAgreeing: 3, consensus: "strong", disputeNotes: "Multiple official sources agree recreational harvest is illegal in California and prohibited in Oregon, with only limited licensed harvest in WA/BC. Edibility itself is undisputed where legal." },
  },
  {
    id: "feather-boa-kelp",
    commonNames: ["Feather Boa Kelp", "Feather-boa Kelp"],
    scientific: "Egregia menziesii",
    group: "kelp",
    habitat: "Rocky low-intertidal and shallow subtidal of moderately-to-fully exposed open coast; attaches to rock and boulders, long fronds streaming in the surge. A perennial brown alga ranging from Alaska to Baja California.",
    tidalZone: "low",
    regionsPNW: ["California", "Bay Area", "North Coast", "Mendocino", "Redwood Coast", "Oregon", "Washington", "Olympic", "British Columbia"],
    harvestMonths: [4, 5, 6, 7],
    peakMonths: [4, 5, 6],
    seasonCue: { tempSensitive: false, notes: "New spring growth and the little floats ('kelp olives') are best from about April through June; harvest young tender tissue and the pea-sized floats rather than old leathery fronds." },
    bestTide: "Minus low tides (around -0.5 ft or lower) that expose low-intertidal rock and the trailing fronds",
    edibleParts: ["pneumatocyst", "blade"],
    edibility: "edible",
    preparation: "The prized parts are the small pea-sized floats (pneumatocysts), the 'olives of the ocean': blanch briefly for a crisp pop, or brine/pickle them as a garnish (fish tacos, martinis, salads). Young blades can be blanched or dried. The tough main frond is often considered too leathery/metallic to eat.",
    cautions: "Not toxic and not a biotoxin vector, but harvest sustainably: take only a few floats/blades per plant across many plants and NEVER remove the holdfast — cut above it so the plant regrows. Slippery, surge-swept low-intertidal rocks are a slip/sneaker-wave hazard. Avoid harvesting in marine protected areas.",
    biotoxinNotes: "Seaweeds do not accumulate PSP/shellfish biotoxins, but they can carry pollutants — harvest only from clean, well-flushed open-coast water away from harbors, marinas, and outfalls; rinse in clean seawater.",
    regulations: "California: legal recreational harvest with a sport-fishing license (16+); daily limit is 10 lb wet weight in the aggregate for kelp and other marine algae, harvested by hand/cutting and leaving the holdfast attached; NOT among the protected algae (unlike sea palm). No take in state marine reserves. Washington and Oregon: allow seaweed harvest under a license with state daily limits (e.g., WA ~10 lb/day wet weight); check WDFW/ODFW.",
    identification: {
      form: "One or more very long, flattened, strap-like main axes fringed on both edges with many small blades and pea-sized floats — resembling a feather boa",
      color: "Olive-brown to dark brown/black",
      texture: "Leathery, rough-surfaced main strap; small rubbery bead-like floats",
      size: "Fronds commonly 2-5 m long, sometimes longer",
      holdfast: "Conspicuous branching/knobby holdfast gripping rock",
      keyFeatures: ["Long flat strap fringed with small blades and pea-sized floats (the 'boa' look)", "Numerous small round floats, not one big float", "Rough, often bumpy central axis", "Low intertidal/subtidal on exposed rock"],
    },
    lookalikes: [
      { name: "Giant kelp", scientific: "Macrocystis pyrifera", danger: "edible", distinguishingFeature: "Each individual blade has its own single teardrop float at its base; blades are larger and corrugated, not a fringed flat strap.", keyFeatures: ["One float per blade", "Large corrugated blades", "Mainly subtidal canopy kelp"] },
      { name: "Bull kelp", scientific: "Nereocystis luetkeana", danger: "edible", distinguishingFeature: "Single large round float at the top of a long whip stipe with a cluster of long blades; no fringing bead floats.", keyFeatures: ["One big round float/bulb", "Long hollow whip stipe", "Blades only at the top"] },
    ],
    culinary: { flavor: "Briny, oceanic, umami; floats are crisp and pop when bitten (main frond can taste metallic/leathery)", uses: "Pickled/brined 'kelp olives', blanched float garnish on tacos or in salads, dried kelp snacks/seasoning", preservation: "Brine/pickle the floats; air-dry young blades" },
    conservationNotes: "Common and not of conservation concern; an important habitat-forming kelp and food for urchins/snails. Harvest lightly, leave holdfasts, and spread take across many plants to preserve buoyancy and regrowth.",
    sources: [
      { name: "CDFW - Recreational Harvest of Kelp and Other Marine Algae (10 lb limit)", url: "https://wildlife.ca.gov/Conservation/Marine/Kelp/Recreational-Harvest" },
      { name: "NOAA/SIMoN Sanctuary - Feather boa kelp (Egregia menziesii)", url: "https://sanctuarysimon.org/dbtools/species-database/id/73/egregia/menziesii/feather-boa-kelp" },
      { name: "NPS Cabrillo National Monument - Feather Boa Kelp", url: "https://www.nps.gov/cabr/blogs/creature-feature-feather-boa-kelp-egregia-menziesii.htm" },
    ],
    verification: { sourcesAgreeing: 3, consensus: "strong", disputeNotes: "Edibility of the floats ('kelp olives') and the leathery main frond is consistently reported. California recreational harvest is legal under the 10-lb aggregate algae limit (unlike protected sea palm); verify state daily limits and MPA closures." },
  },
];

export const GENERATED_OCEAN: OceanSpecies[] = SEED.map((o) => ({
  ...o,
  autoCompiled: true,
  verification: { ...o.verification, lastVerified: LAST_VERIFIED },
}));
