/**
 * Pipeline-added wild edible plants (Tahoe–Truckee / Sierra Nevada). Researched
 * the same way as the curated seed set and merged into PLANT_CATALOG via
 * lib/plant-catalog.ts. All marked autoCompiled → "verify before foraging".
 *
 * Includes roots/tubers with DEADLY lookalikes (camas ↔ death camas; yampah ↔
 * water/poison hemlock) flagged edible-with-caution with mandatory-ID prep, and
 * three toxic/deadly warning entries (baneberry, snowberry, larkspur) that
 * lookalikes deep-link to.
 */
import type { PlantSpecies } from "../../plant-types";
import type { Verification } from "../../species-types";

type RawPlant = Omit<PlantSpecies, "verification" | "autoCompiled"> & {
  verification: Omit<Verification, "lastVerified">;
};

const LAST_VERIFIED = "2026-07-05";

const SEED: RawPlant[] = [
  {
    id: "lanceleaf-spring-beauty",
    commonNames: ["Lanceleaf Spring Beauty", "Western Spring Beauty", "Mountain Potato", "Indian Potato"],
    scientific: "Claytonia lanceolata",
    family: "Montiaceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 5, max: 20 },
    habitat: "Moist montane to subalpine and alpine meadows, streambanks, and open slopes, often flowering at the receding edge of melting snowbanks; also sagebrush steppe and open conifer forest floors.",
    elevationM: { min: 1500, max: 3500 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra"],
    harvestMonths: [5, 6, 7],
    peakMonths: [6, 7],
    seasonCue: { tempSensitive: true, notes: "Snowmelt-driven ephemeral; flowers within days of snow retreat and withers by mid-summer, so timing shifts by elevation and snowpack. Dig corms while the paired leaves and flowers are still present to confirm ID." },
    edibleParts: ["young-leaves", "leaves", "flowers", "tuber"],
    edibility: "edible",
    preparation: "The small round corm (the 'mountain potato') is dug when the plant is in leaf/flower. Raw it is crisp and radish-like; boiled, steamed, or baked it is tender like a small potato. Leaves and flowers are edible raw in salads or lightly cooked. Skins rub off after boiling.",
    cautions: "Corms are small and populations patchy; over-digging depletes slow-growing montane colonies. Because death camas and other bulb/corm plants grow in the same wet meadows, never dig unlabeled underground parts — confirm the living plant by its two lance-shaped stem leaves and 5-petaled pink/white flowers first.",
    toxicityNotes: "No toxic parts; the entire plant is edible. Main risk is misidentification of the corm if dug without the aboveground plant attached in meadows shared with toxic bulbs.",
    identification: {
      leaves: "A single opposite pair of thick, smooth, lance-shaped leaves borne midway up the flowering stem, plus occasional basal leaves.",
      stem: "Short, erect, unbranched, succulent stem 5-20 cm tall arising from a deep round corm.",
      flowers: "Loose raceme of 3-15 star-shaped 5-petaled flowers, white to pink with darker pink veins and often yellow spots near the petal bases.",
      fruit: "Small 3-valved capsule containing shiny black seeds.",
      root: "A single roundish corm 1-3 cm wide, buried several cm deep; white starchy interior.",
      aroma: "Faint, fresh; raw corm mildly radish-like. No onion or acrid odor.",
      height: "5-20 cm tall.",
      keyFeatures: ["Two lance-shaped leaves on the stem", "Pink-veined white-to-pink star flowers", "Deep round corm ('mountain potato')", "Flowers at snowmelt in montane meadows"],
    },
    lookalikes: [
      { name: "Death camas (co-occurring, dormant risk)", scientific: "Toxicoscordion venenosum", danger: "deadly", distinguishingFeature: "Death camas has grass-like V-keeled basal leaves from an onion-like bulb (not a round corm) and cream 6-tepal star flowers; it shares wet meadows, so never dig unmarked underground parts. Spring beauty has a round corm and 2 broad stem leaves.", catalogId: "meadow-death-camas", keyFeatures: ["Onion-like layered bulb, not a round corm", "Grass-like keeled leaves", "6-tepaled cream flowers"] },
      { name: "Miner's lettuce / other Claytonia", scientific: "Claytonia perfoliata", danger: "edible", distinguishingFeature: "Congeners such as miner's lettuce have round perfoliate leaves and lack the swollen corm; all are edible, so confusion within the genus is not dangerous.", catalogId: "miners-lettuce", keyFeatures: ["Succulent smooth leaves", "Small 5-petaled white/pink flowers", "Mild non-acrid taste"] },
    ],
    culinary: { flavor: "Raw corm crisp and radish-like; cooked it is mild, sweet, and potato-like. Leaves mild and succulent.", uses: "Boil, steam, or roast corms as a wild potato; add raw leaves and flowers to salads or cook as greens.", preservation: "Corms can be dried for storage and later rehydrated; best eaten fresh." },
    conservationNotes: "A slow-reproducing montane ephemeral and a traditional First Foods staple. Colonies recover slowly from digging — take only a fraction of any patch and leave smaller corms to regrow.",
    sources: [
      { name: "Wikipedia: Claytonia lanceolata", url: "https://en.wikipedia.org/wiki/Claytonia_lanceolata" },
      { name: "Calflora: Claytonia lanceolata", url: "https://www.calflora.org/app/taxon?crn=2235" },
      { name: "Lady Bird Johnson Wildflower Center: Claytonia lanceolata", url: "https://www.wildflower.org/plants/result.php?id_plant=clla2" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: null },
  },
  {
    id: "bitterroot",
    commonNames: ["Bitterroot", "Bitter Root", "Rock Rose", "Spatlum"],
    scientific: "Lewisia rediviva",
    family: "Montiaceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 2, max: 8 },
    habitat: "Dry, open, gravelly and rocky soils in sagebrush scrub, pinyon-juniper woodland, and open ponderosa/Jeffrey pine slopes on the arid east side; requires full sun and sharp drainage. Leaves appear in spring and wither before the flowers open.",
    elevationM: { min: 1200, max: 3000 },
    regionsPNW: ["Eastern Sierra", "Great Basin", "Carson Range", "Truckee"],
    harvestMonths: [4, 5, 6],
    peakMonths: [5],
    seasonCue: { tempSensitive: true, notes: "Best dug in spring just before or as flower buds appear, when the very bitter outer bark of the root slips off easily; the plant is nearly invisible after flowering when leaves have withered." },
    edibleParts: ["root"],
    edibility: "edible-with-caution",
    preparation: "Dig the fleshy taproot in spring before flowering. Peel off the bitter reddish outer skin (it slips off readily at that season), then boil, steam, or pit-roast until tender; the cooked root swells and softens. Traditionally dried for storage and later boiled into gruel. Summer roots turn intensely bitter and are not palatable.",
    cautions: "Root is edible but very bitter unless peeled and cooked at the right season; the bitter outer layer must be removed. Culturally sensitive and slow to regenerate — do not over-harvest. Positive ID is easy in flower but the plant is cryptic when dormant.",
    toxicityNotes: "No toxic compounds of concern in the peeled cooked root; bitterness (saponin/tannin-like) is the deterrent and is reduced by peeling and boiling. Confirm the rosette/flower before digging.",
    identification: {
      leaves: "A ground-level rosette of many short, thick, fleshy, club-shaped grayish leaves that emerge in late winter and wither at or before bloom.",
      stem: "Very short flowering stalks (2-8 cm) each bearing a single flower, with a whorl of small bracts below the flower.",
      flowers: "Large, showy, many-petaled (12-18 tepals) rose-pink to white flowers up to 5-6 cm across, opening in sun and seeming to sit nearly on the ground.",
      fruit: "Egg-shaped capsule with several shiny nearly-round dark seeds.",
      root: "A thick, fleshy, carrot-like taproot, often forked, with a bitter reddish-brown removable outer bark; regrows even from dried-out roots (hence 'rediviva').",
      aroma: "Not notably aromatic; peeled root mild, outer bark intensely bitter.",
      height: "2-8 cm; low and ground-hugging.",
      keyFeatures: ["Large many-petaled pink flower sitting almost on bare gravel", "Fleshy cylindrical leaf rosette that withers at bloom", "Forked fleshy taproot with bitter slip-off skin", "Dry rocky sagebrush/pine sites"],
    },
    lookalikes: [
      { name: "Pygmy / alpine lewisias", scientific: "Lewisia pygmaea", danger: "edible", distinguishingFeature: "Smaller-flowered relatives with fewer petals and thinner roots; also Montiaceae and not toxic, so confusion is not dangerous.", keyFeatures: ["Fleshy succulent leaves", "Pink 5-9 petaled flowers", "Non-bitter smaller roots"] },
      { name: "Pussypaws", scientific: "Calyptridium monospermum", danger: "edible", distinguishingFeature: "Also a low Montiaceae rosette of dry gravel, but with dense papery ball-like flower clusters on radiating stems rather than one large showy flower; harmless.", keyFeatures: ["Flat basal rosette", "Papery pom-pom flower heads", "Thin non-fleshy root"] },
    ],
    culinary: { flavor: "Peeled cooked root is starchy and mildly bitter-sweet; the reddish skin and out-of-season roots are strongly bitter.", uses: "Boil, steam, or pit-roast peeled roots; historically dried and stored, then reconstituted into porridge or mixed with berries.", preservation: "Dries well for long storage; dried roots keep for years and rehydrate on cooking." },
    conservationNotes: "A sacred First Foods root of deep cultural importance to the Washoe, Northern Paiute, Western Shoshone, Salish and other peoples who still gather it. Slow-growing on fragile arid soils; harvest only where abundant, leave smaller roots, and respect tribal harvesting areas.",
    sources: [
      { name: "USDA NRCS Plant Guide: Lewisia rediviva", url: "https://plants.sc.egov.usda.gov/DocumentLibrary/plantguide/pdf/cs_lere7.pdf" },
      { name: "USFS FEIS: Lewisia rediviva", url: "https://www.fs.usda.gov/database/feis/plants/forb/lewred/all.html" },
      { name: "Calscape: Lewisia rediviva (Bitter Root)", url: "https://calscape.org/Lewisia-rediviva-(Bitter-Root)" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: null },
  },
  {
    id: "yampah",
    commonNames: ["Yampah", "Bolander's Yampah", "Wild Caraway", "Squaw Root"],
    scientific: "Perideridia bolanderi",
    family: "Apiaceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 30, max: 90 },
    habitat: "Moist to seasonally moist montane and subalpine meadows, grassy flats, and open forest openings with abundant spring moisture. Grows in and near meadows where deadly water hemlock also occurs.",
    elevationM: { min: 1200, max: 3000 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra"],
    harvestMonths: [7, 8, 9],
    peakMonths: [7, 8],
    seasonCue: { tempSensitive: true, notes: "Identify and dig ONLY while the plant is in flower/seed (mid-to-late summer) so the umbel, foliage, and aroma can be verified. Tubers are starchiest in late summer as the tops die back. Do not harvest based on roots alone." },
    edibleParts: ["tuber", "seeds"],
    edibility: "edible-with-caution",
    preparation: "MANDATORY ID BEFORE EATING: Yampah is a carrot-family plant with white flower umbels that closely resemble DEADLY water hemlock (Cicuta) and poison hemlock (Conium). Only harvest plants identified in full flower with an expert-level positive ID confirming ALL of: (1) slender green stem with NO purple blotches; (2) few narrow, grass-like leaflets, NOT coarse fern-like leaves; (3) small clustered tubers, NOT a thickened chambered rootstock that oozes yellow/reddish oily fluid (that is water hemlock, deadly); (4) a sweet parsley/carrot/anise aroma, NOT the musty 'mousy' odor of poison hemlock. When confirmed, eat raw (crisp like water chestnut) or boil/roast; dry tubers to flour; use seeds as a caraway-like spice. If in ANY doubt, do not eat.",
    cautions: "DEADLY LOOKALIKES. Fatalities have occurred when foragers dug water hemlock roots believing them to be yampah. Never dig a carrot-family root without a confirmed flowering-plant ID. A single mistaken water-hemlock root can kill. Avoid entirely unless you are an expert.",
    toxicityNotes: "Yampah itself is non-toxic. The danger is confusion with Cicuta douglasii (cicutoxin, often fatal) and Conium maculatum (coniine, paralysis and respiratory failure), both widespread in the same Sierra meadows. Cut water hemlock rootstock is chambered and exudes yellowish oil turning reddish-brown in air.",
    identification: {
      leaves: "Few, mostly basal, divided into narrow, almost grass-like linear leaflets 10-20 cm long; foliage sparse and fine, not coarse or fern-like.",
      stem: "Slender, erect, hollow, green (never purple-spotted), 30-90 cm.",
      flowers: "Compound umbels of many small white flowers in rounded clusters, blooming mid-to-late summer.",
      fruit: "Small ribbed oval seeds with a sweet caraway/anise scent when crushed.",
      root: "One or a few small, clustered tuberous roots ~2-8 cm long, solid white flesh; NOT a single chambered rootstock.",
      aroma: "KEY: sweet, pleasant, parsley/carrot/anise-caraway scent. Any musty 'mouse' smell (poison hemlock) or raw-parsnip smell from a chambered oozing root (water hemlock) means STOP — deadly.",
      height: "30-90 cm.",
      keyFeatures: ["Smooth GREEN stem with no purple blotches", "Sparse narrow grass-like leaflets", "Small clustered solid tubers (not chambered)", "Sweet parsley/anise aroma, never musty or acrid"],
    },
    lookalikes: [
      { name: "Water hemlock", scientific: "Cicuta douglasii", danger: "deadly", distinguishingFeature: "One of the most poisonous plants in North America. Stout, often purple-streaked hollow stem, coarse sharply-toothed leaflets whose veins END IN THE NOTCHES between teeth, and a thickened rootstock that is CHAMBERED and oozes yellowish oil turning reddish-brown in air. Yampah has slender green stems, fine narrow leaflets, small solid clustered tubers, and a sweet aroma.", catalogId: "western-water-hemlock", keyFeatures: ["Chambered rootstock with yellow-red oily sap", "Leaf veins ending in the notches, not the tips", "Stout stem, wet-ground habitat", "Convulsant, rapidly fatal"] },
      { name: "Poison hemlock", scientific: "Conium maculatum", danger: "deadly", distinguishingFeature: "Tall biennial with smooth hollow stems conspicuously blotched with PURPLE, finely-dissected fern-like leaves, and a musty 'mousy' odor; single white carrot-like taproot. Yampah stems are green and unspotted, leaves sparse and grass-like, aroma sweet.", catalogId: "poison-hemlock", keyFeatures: ["Purple-spotted smooth stem", "Fern-like finely dissected leaves", "Musty mouse-like odor", "White carrot-like taproot"] },
    ],
    culinary: { flavor: "Raw tubers crisp and mildly sweet like water chestnut; cooked, parsnip-like. Seeds warm and caraway/anise-like.", uses: "Boil, roast, or eat raw once positively identified; dry and grind tubers to flour; use seeds as a caraway substitute.", preservation: "Tubers dry well for storage and can be ground to meal; seeds dried as spice." },
    conservationNotes: "A historically important root food for many Great Basin and Sierra peoples (the source of the place name 'Yampa'). Meadow populations are localized; harvest sparingly. Given the deadly lookalikes, not recommended for beginners at all.",
    sources: [
      { name: "Wikipedia: Perideridia", url: "https://en.wikipedia.org/wiki/Perideridia" },
      { name: "Colorado State Univ. Guide to Poisonous Plants: Water Hemlock (Cicuta)", url: "https://poisonousplants.cvmbs.colostate.edu/plant/47" },
      { name: "Cultivariable: How to Grow Yampah (Perideridia spp.)", url: "https://www.cultivariable.com/instructions/root-crops/how-to-grow-yampah/" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "All sources agree yampah is edible and dangerously similar to deadly water and poison hemlock; sources uniformly warn against harvest without expert ID." },
  },
  {
    id: "common-camas",
    commonNames: ["Common Camas", "Small Camas", "Blue Camas", "Quamash"],
    scientific: "Camassia quamash",
    family: "Asparagaceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 20, max: 70 },
    habitat: "Montane meadows, wet swales, vernally moist flats, and streamsides that are wet in spring and dry by summer. Frequently grows intermixed with deadly death camas.",
    elevationM: { min: 1500, max: 2500 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range"],
    harvestMonths: [5, 6, 7],
    peakMonths: [6, 7],
    seasonCue: { tempSensitive: true, notes: "Harvest ONLY while flowering, when the blue color is confirmed. Bloom follows snowmelt, roughly late spring to mid-summer by elevation. NEVER dig dormant bulbs — without the blue flower you cannot safely separate camas from deadly death camas." },
    edibleParts: ["bulb"],
    edibility: "edible-with-caution",
    preparation: "MANDATORY ID BEFORE EATING: Camas bulbs are nearly identical to DEADLY death camas (Toxicoscordion venenosum). Only dig bulbs from plants confirmed in BLOOM with clearly BLUE-to-violet 6-tepal flowers. Death camas has cream/white flowers; when neither is in flower the bulbs are indistinguishable — dig one plant at a time, keeping the flowering stalk attached to each bulb. Cooking does NOT destroy death camas toxin. Once confirmed, camas bulbs need LONG slow cooking, traditionally pit-roasted 24-36+ hours (or slow-baked/boiled many hours) to convert indigestible inulin into sweet fructose; the result is dark, sweet, molasses-like. Undercooked bulbs cause gas and GI upset.",
    cautions: "DEADLY LOOKALIKE. Death camas grows in the same meadows and its bulb looks the same. Only ever harvest camas in flower with blue confirmed; never harvest dormant bulbs, mixed patches, or on someone else's say-so. Even a few death camas bulbs can kill an adult.",
    toxicityNotes: "Camas bulb itself is non-toxic (but must be well-cooked for digestibility). The lethal risk is Toxicoscordion venenosum, whose bulbs contain zygacine/zygadenine steroidal alkaloids; as few as two bulbs can kill an adult and toxins are NOT degraded by cooking.",
    identification: {
      leaves: "Several long, narrow, grass-like basal leaves with a channeled midrib, 20-60 cm, softer and broader than death camas leaves.",
      stem: "Single leafless flowering stalk 20-70 cm tall rising from the bulb.",
      flowers: "Open raceme of 10-40 star-shaped flowers, each with 6 tepals of deep BLUE to blue-violet (rarely white). This blue color is the single most important safety character.",
      fruit: "3-chambered capsule; withering blue tepals often persist and twist over the developing capsule.",
      root: "Deep, onion-like layered bulb 1.5-4 cm across; indistinguishable from death camas bulb by eye.",
      aroma: "Bulb bland/starchy with NO onion smell — this only rules OUT wild onion; it does NOT distinguish camas from death camas, which also lacks onion odor.",
      height: "20-70 cm.",
      keyFeatures: ["BLUE 6-tepal star flowers in an open raceme (the safety key)", "Grass-like basal leaves", "Wet spring meadows", "Onion-like layered bulb identical to deadly death camas"],
    },
    lookalikes: [
      { name: "Death camas (meadow death camas)", scientific: "Toxicoscordion venenosum", danger: "deadly", distinguishingFeature: "The critical deadly confusion. Bulbs are essentially identical to camas. Distinguished ONLY in flower: death camas has cream/greenish-WHITE 6-tepal flowers and narrower, sharply V-keeled leaves, often on drier ground. Camas flowers are BLUE. If not in flower, the two cannot be told apart — do not harvest.", catalogId: "meadow-death-camas", keyFeatures: ["Cream/white flowers (never blue)", "Sharply V-keeled narrow leaves", "Bulb identical to camas", "Contains lethal zygacine alkaloids"] },
      { name: "Wild onion", scientific: "Allium spp.", danger: "edible", distinguishingFeature: "Also has grass-like leaves and a bulb but smells strongly of ONION/garlic when crushed; camas and death camas have NO onion smell. A strong onion odor means it is an Allium, but absence of onion smell does not confirm camas.", catalogId: "sierra-swamp-onion", keyFeatures: ["Strong onion/garlic odor", "Umbel of flowers (not a raceme)", "Membranous bulb sheath"] },
    ],
    culinary: { flavor: "Long-cooked bulbs are sweet, dark, sticky, and molasses- or fig-like; undercooked they are fibrous and cause flatulence.", uses: "Pit-roast, slow-bake, or long-boil; mash into cakes, sweeten dishes, or dry. Historically a major carbohydrate staple.", preservation: "Cooked bulbs were pressed into cakes and dried for winter storage." },
    conservationNotes: "Camas meadows are of profound cultural importance to Plateau, Great Basin, and other Indigenous peoples, who tended them with fire and selective harvest. Harvest only from abundant populations, replant small bulbs, and respect that many camas meadows are managed or sacred sites.",
    sources: [
      { name: "Wikipedia: Camassia quamash", url: "https://en.wikipedia.org/wiki/Camassia_quamash" },
      { name: "USFS FEIS: Camassia quamash (small camas)", url: "https://research.fs.usda.gov/feis/species-reviews/camqua" },
      { name: "Calscape: Toxicoscordion venenosum (Death Camas)", url: "https://calscape.org/Toxicoscordion-venenosum-(Death-Camas)" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "Universal agreement that camas is edible only when the blue flower confirms ID and that death camas is deadly and bulb-identical; consensus that dormant bulbs must never be harvested." },
  },
  {
    id: "arrowleaf-balsamroot",
    commonNames: ["Arrowleaf Balsamroot", "Oregon Sunflower", "Balsamroot"],
    scientific: "Balsamorhiza sagittata",
    family: "Asteraceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 20, max: 80 },
    habitat: "Open, dry sunny slopes, sagebrush steppe, grassy meadows, and open ponderosa/Jeffrey pine and juniper woodland; deep-rooted and drought-tolerant on well-drained soils.",
    elevationM: { min: 1200, max: 2800 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra", "Great Basin"],
    harvestMonths: [4, 5, 6, 7, 8],
    peakMonths: [5, 6],
    seasonCue: { tempSensitive: true, notes: "Young shoots and peeled flower stems in early spring; roots best dug in spring or fall; seeds collected mid-to-late summer as flower heads dry. Bloom roughly May-July by elevation." },
    edibleParts: ["young-leaves", "shoots", "stems", "root", "seeds"],
    edibility: "edible",
    preparation: "Young spring shoots and peeled immature flower stalks are eaten raw or cooked like a vegetable. The large taproot is resinous and pine-bitter raw; traditionally baked or steamed slowly (pit-baked up to ~3 days) to break down resins and inulin into a sweeter food. Oil-rich seeds are eaten roasted and ground into meal or pinole.",
    cautions: "Aboveground parts and raw root carry a strong balsam/pine resin flavor that many find unpalatable and that can cause mild GI upset if eaten raw in quantity; long cooking improves the root. Otherwise non-toxic. Deep-rooted plants are slow to replace — harvest roots sparingly.",
    toxicityNotes: "No significant toxicity reported; widely documented as edible and also used medicinally. Main drawback is resinous bitterness, not poison.",
    identification: {
      leaves: "Large basal rosette of distinctly arrowhead-shaped, silvery-hairy grayish-green leaves 10-45 cm long, all arising from the base on long petioles.",
      stem: "Leafless or nearly leafless flowering stalks, each typically bearing a single head; 20-80 cm tall.",
      flowers: "Large sunflower-like yellow heads 6-10 cm across with yellow ray and disk florets.",
      fruit: "Dry seed-like achenes (edible oily seeds), hairless.",
      root: "Very large, deep, woody, resinous taproot with a balsam/pine scent.",
      aroma: "Whole plant and sap smell strongly of balsam/pine resin; crushed foliage pungent.",
      height: "20-80 cm.",
      keyFeatures: ["Silvery arrowhead-shaped basal leaves", "Big yellow sunflower heads on nearly leafless stalks", "Balsam/pine-scented resinous taproot", "Dry open sunny slopes"],
    },
    lookalikes: [
      { name: "Mule's ears", scientific: "Wyethia mollis", danger: "edible-with-caution", distinguishingFeature: "Similar big yellow sunflower heads but leaves are large, elliptical/tongue-shaped (not arrowhead), often borne along the flowering stem whereas balsamroot leaves are all basal and arrow-shaped. Not a preferred food (resinous) but not deadly.", keyFeatures: ["Elliptical tongue-shaped leaves, not arrow-shaped", "Leaves borne up the stem", "Coarser, greener foliage"] },
    ],
    culinary: { flavor: "Young shoots and peeled stems mild and celery/sunflower-like; root sweet-starchy after long cooking but resinous/bitter raw; roasted seeds nutty and oil-rich.", uses: "Steam or saute young shoots and peeled stems; slow-bake or steam roots; roast and grind seeds into meal, pinole, or press for oil.", preservation: "Roots can be dried after cooking; seeds dry and store well as meal." },
    conservationNotes: "A widespread and traditionally important food and medicine plant across the Great Basin and interior West. Deep taproots make mature plants slow to regenerate after digging; harvest roots only where locally abundant and favor seeds/shoots for lower impact.",
    sources: [
      { name: "USFS FEIS: Balsamorhiza sagittata", url: "https://research.fs.usda.gov/feis/species-reviews/balsag" },
      { name: "USFS Celebrating Wildflowers: Arrowleaf Balsamroot", url: "https://www.fs.usda.gov/wildflowers/plant-of-the-week/balsamorhiza_sagittata.shtml" },
      { name: "Lady Bird Johnson Wildflower Center: Balsamorhiza sagittata", url: "https://www.wildflower.org/plants/result.php?id_plant=basa3" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: null },
  },
  {
    id: "curly-dock",
    commonNames: ["Curly Dock", "Curled Dock", "Yellow Dock", "Sour Dock"],
    scientific: "Rumex crispus",
    family: "Polygonaceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 50, max: 150 },
    habitat: "Disturbed, moist ground — roadsides, ditches, streambanks, pond and meadow margins, irrigated pastures, and campground edges throughout the Tahoe-Truckee foothill and montane zone.",
    elevationM: { min: 200, max: 2500 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra", "Great Basin"],
    harvestMonths: [3, 4, 5, 6, 7, 8, 9, 10],
    peakMonths: [4, 5],
    seasonCue: { tempSensitive: true, notes: "Harvest leaves while young in early spring; they turn bitter and more oxalate-rich after the plant bolts in summer heat. Seeds ripen and turn rusty-brown in late summer to fall." },
    edibleParts: ["young-leaves", "leaves", "seeds"],
    edibility: "edible-with-caution",
    preparation: "Pick young, tender leaves before flowering and strip them from the midrib. Steam, boil (change the water once for a milder result), or sauté like spinach; older leaves are too sour/bitter. Winnow mature seeds and grind the reddish-brown achenes into a nutty flour, or parch and add to porridge.",
    cautions: "Contains oxalic acid and soluble oxalates — eat young leaves in moderation and cook (optionally changing the water) to reduce the oxalate load. Avoid large raw quantities, especially if prone to kidney stones, gout, or kidney disease. Leaves grow more bitter and higher in oxalates with age.",
    toxicityNotes: "Not otherwise toxic to humans, but high oxalate intake can be harmful in quantity; large ingestions have caused oxalate poisoning in livestock.",
    identification: {
      leaves: "Lance-shaped, 15-30 cm, with distinctly wavy/curly margins; a basal rosette in year one, then alternate up the stem, each with a papery sheath (ocrea) wrapping the stem at the leaf base.",
      stem: "One to few erect, ridged/grooved stems, often reddish-tinged, unbranched below the flower cluster.",
      flowers: "Numerous small greenish flowers turning reddish-brown, in dense whorled clusters on a branched terminal panicle.",
      fruit: "Three-winged reddish-brown achenes; seed stalks persist and turn rusty brown into winter.",
      root: "Stout, yellow-orange taproot.",
      aroma: "Faintly sour; not strongly aromatic.",
      height: "50-150 cm in flower.",
      keyFeatures: ["Wavy/curly leaf margins", "Papery ocrea sheath at each leaf base", "Rusty-brown seed stalks that persist into winter", "Yellow taproot"],
    },
    lookalikes: [
      { name: "Broad-leaved Dock", scientific: "Rumex obtusifolius", danger: "edible", distinguishingFeature: "Broader, flat (not curly-margined) leaves with a heart-shaped base; also an edible dock treated the same way.", keyFeatures: ["Flat wide leaves", "Reddish leaf stalks", "Toothed seed valves"] },
    ],
    culinary: { flavor: "Tart and lemony-spinach-like when young, increasingly sour and bitter with age.", uses: "Young leaves steamed, boiled, or sautéed like spinach or added to soups; ripe seeds winnowed and ground into a nutty flour.", preservation: "Blanch and freeze leaves; dry and store seeds for grinding." },
    conservationNotes: "Non-native, widespread weed; no conservation concern — harvesting freely is beneficial. Avoid plants from herbicide-treated ground.",
    sources: [
      { name: "Calflora — Rumex crispus", url: "https://www.calflora.org/app/taxon?crn=7215" },
      { name: "UC IPM Weed Gallery — Curly Dock", url: "https://ipm.ucanr.edu/PMG/WEEDS/curly_dock.html" },
      { name: "Cal-IPC Plant Profile — Rumex crispus", url: "https://www.cal-ipc.org/plants/profile/rumex-crispus-profile/" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "Sources agree young leaves and seeds are edible and on the oxalic-acid caution; they differ only on how strictly to limit raw intake." },
  },
  {
    id: "sheep-sorrel",
    commonNames: ["Sheep Sorrel", "Red Sorrel", "Field Sorrel", "Sour Grass"],
    scientific: "Rumex acetosella",
    family: "Polygonaceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 10, max: 45 },
    habitat: "Dry to moist disturbed, acidic soils — roadsides, trail edges, logged or burned openings, decomposed-granite slopes, meadows, and lawns across the Sierra foothill and montane belt.",
    elevationM: { min: 300, max: 2900 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra", "Great Basin"],
    harvestMonths: [4, 5, 6, 7, 8, 9, 10],
    peakMonths: [5, 6],
    seasonCue: { tempSensitive: true, notes: "Leaves are mildest and most tender in cool spring; hot summer weather makes them tougher and sharper. Fresh tender growth flushes again after rain." },
    edibleParts: ["young-leaves", "leaves"],
    edibility: "edible-with-caution",
    preparation: "Gather small young arrowhead-shaped leaves. Eat raw in modest amounts in salads or as a tart garnish, or cook briefly into sauces, soups, and purées (the classic sorrel sauce). Boiling and rinsing reduces oxalates if eating larger quantities.",
    cautions: "High in oxalic acid/oxalates — the source of its lemony tang. Eat in small amounts raw; avoid large servings, particularly if prone to kidney stones, gout, or kidney disease. Cooking and rinsing lowers oxalate content.",
    toxicityNotes: "Not toxic in normal food amounts; excessive oxalate intake is the only concern for humans and can affect grazing livestock in quantity.",
    identification: {
      leaves: "Small, distinctive arrowhead/halberd shape with two outward-flaring basal lobes; smooth, somewhat fleshy.",
      stem: "Slender, wiry, often reddish flowering stems arising from creeping rhizomes; forms spreading patches.",
      flowers: "Tiny, dioecious; reddish (male) to yellowish-green, on slender terminal spikes that give colonies a rusty-red cast.",
      fruit: "Minute golden- to reddish-brown achenes.",
      root: "Slender, shallow, spreading rhizomes forming mats.",
      aroma: "Sour, lemony when a leaf is chewed.",
      height: "10-45 cm.",
      keyFeatures: ["Arrowhead leaves with two flaring basal lobes", "Sharp sour/lemony taste", "Reddish flowering stems tinting patches red", "Rhizomatous, mat-forming"],
    },
    lookalikes: [
      { name: "Mountain Sorrel", scientific: "Oxyria digyna", danger: "edible", distinguishingFeature: "Rounded kidney-shaped basal leaves (not arrow-lobed); an edible high-elevation sour green.", catalogId: "mountain-sorrel", keyFeatures: ["Kidney/round leaves", "Sour taste", "Alpine rocky sites"] },
    ],
    culinary: { flavor: "Bright, sour, lemony — like a blend of lemon and green apple.", uses: "Raw in small amounts in salads and as a garnish; blended into sorrel sauces, soups, and pestos.", preservation: "Best used fresh; can be cooked into a sauce or frozen as a purée." },
    conservationNotes: "Non-native, aggressive rhizomatous weed; no conservation concern — harvest freely. Avoid sprayed ground.",
    sources: [
      { name: "Wikipedia — Rumex acetosella", url: "https://en.wikipedia.org/wiki/Rumex_acetosella" },
      { name: "NC State Extension — Rumex acetosella", url: "https://plants.ces.ncsu.edu/plants/rumex-acetosella/" },
      { name: "Forager Chef — Sheep Sorrel", url: "https://foragerchef.com/sheep-sorrel/" },
    ],
    verification: { sourcesAgreeing: 3, consensus: "strong", disputeNotes: "Universal agreement on edible sour leaves and the oxalate caution; guidance varies only on the safe raw quantity." },
  },
  {
    id: "american-bistort",
    commonNames: ["American Bistort", "Western Bistort", "Smokeweed"],
    scientific: "Bistorta bistortoides",
    family: "Polygonaceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 10, max: 70 },
    habitat: "Moist to wet subalpine and montane meadows, streambanks, seeps, and lakeshores, often in lodgepole, red-fir, and subalpine zones from the Tahoe crest to the high Sierra.",
    elevationM: { min: 1800, max: 3700 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra"],
    harvestMonths: [6, 7, 8, 9],
    peakMonths: [7, 8],
    seasonCue: { tempSensitive: true, notes: "Emergence and bloom track snowmelt — leaves appear as meadows thaw (often late June), flowering July-August, roots dug late summer; timing shifts weeks later in high or heavy-snow years." },
    edibleParts: ["root", "young-leaves", "leaves", "seeds"],
    edibility: "edible",
    preparation: "Dig the thick rhizomes (positively identify first — see cautions), scrub, and roast, boil, or fire-roast; soak or leach to cut astringency if bitter. Eat young basal leaves raw or as a cooked potherb. Parch or grind the seeds. Roots and seeds were traditionally dried and stored for winter.",
    cautions: "Roots are astringent and tannin-rich and are best roasted or boiled. CRITICAL: before digging roots in wet meadows, positively identify the plant — deadly death camas grows in the same habitat. Take only where the plant is abundant and where collecting is legal.",
    toxicityNotes: "The plant itself is non-toxic; contains tannins and modest oxalates that make raw roots astringent. Risk comes from misidentifying co-occurring toxic meadow plants, not from the bistort.",
    identification: {
      leaves: "Mostly basal, long-stalked, lance- to oblong-shaped, 10-20 cm; a few small, nearly stalkless leaves up the stem; papery ocrea sheaths present.",
      stem: "A single slender, erect, unbranched flowering stalk.",
      flowers: "One dense, cylindrical, bottlebrush-like terminal spike of small white to pale-pink flowers with protruding stamens.",
      fruit: "Small three-angled, glossy brown achene (seed).",
      root: "Thick, dark, S-shaped/contorted rhizome (the twice-twisted 'bistort' rootstock).",
      aroma: "Flowers can smell slightly rank up close; foliage not strongly aromatic.",
      height: "20-70 cm (dwarfed above 2,300 m).",
      keyFeatures: ["Single white bottlebrush flower spike atop a leafless stalk", "Long-stalked basal leaves", "Thick contorted (S-shaped) rhizome", "Wet subalpine/alpine meadows"],
    },
    lookalikes: [
      { name: "Death Camas", scientific: "Toxicoscordion venenosum", danger: "deadly", distinguishingFeature: "Grows in the same wet meadows; has grass-like, V-channeled leaves and an onion-like bulb (no onion smell), with cream star-shaped flowers in a loose open raceme — NOT bistort's broad basal leaves, dense white spike, and contorted rhizome. Never dig roots without confirming leaf shape and rootstock.", catalogId: "meadow-death-camas", keyFeatures: ["Grass-like folded leaves", "Onion-like bulb without onion odor", "Loose raceme of star-shaped cream flowers"] },
    ],
    culinary: { flavor: "Cooked roots nutty and starchy like chestnut (astringent raw); young leaves mild and slightly tart; seeds nutty.", uses: "Roots roasted, boiled, or added to stews; young leaves as a potherb or salad green; seeds parched or ground into meal.", preservation: "Roots and seeds can be dried and stored for winter." },
    conservationNotes: "Native perennial of sensitive, slow-recovering subalpine/alpine wet meadows. Harvest leaves and seeds sparingly and avoid digging roots in fragile, heavily used, or protected meadows; collecting is prohibited in National Parks and many wilderness areas.",
    sources: [
      { name: "Wikipedia — Bistorta bistortoides", url: "https://en.wikipedia.org/wiki/Bistorta_bistortoides" },
      { name: "Calscape — Western Bistort", url: "https://calscape.org/Bistorta-bistortoides-(Western-Bistort)-2" },
      { name: "Eat The Planet — Western Bistort", url: "https://eattheplanet.org/western-bistort-a-native-american-staple-wild-edible/" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "Agreement that leaves, seeds, and roots are edible; sources differ on root palatability (some rate cooked roots chestnut-like, others emphasize they are tannic, favoring the leaves and seeds)." },
  },
  {
    id: "broadleaf-plantain",
    commonNames: ["Broadleaf Plantain", "Greater Plantain", "Common Plantain", "White Man's Foot"],
    scientific: "Plantago major",
    family: "Plantaginaceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 5, max: 40 },
    habitat: "Compacted, disturbed, moist ground near human activity — trailheads, campgrounds, lawns, roadsides, and town lots in the Tahoe basin and around Truckee; largely absent from wildland high country.",
    elevationM: { min: 300, max: 2200 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra", "Great Basin"],
    harvestMonths: [4, 5, 6, 7, 8, 9],
    peakMonths: [5, 6],
    seasonCue: { tempSensitive: true, notes: "Young rosette leaves are best in spring to early summer before they toughen; tender new growth follows mowing or rain. Seeds ripen mid- to late summer." },
    edibleParts: ["young-leaves", "leaves", "seeds"],
    edibility: "edible",
    preparation: "Use young, tender leaves raw in salads, or cook older leaves as greens after tearing out the tough stringy veins. Simmer or sauté to soften. Immature green seed spikes can be cooked; mature seeds and their husks work like psyllium to thicken foods. Collect only from unsprayed ground.",
    cautions: "Very safe as food; older leaves become tough and fibrous, so favor young leaves or cook them. Do NOT collect from herbicide-treated lawns/roadsides. When gathering a first-year basal rosette, do not confuse it with a hairy foxglove rosette (see lookalikes).",
    toxicityNotes: "Non-toxic; regarded as one of the safest wild edible/medicinal greens.",
    identification: {
      leaves: "Broad oval to egg-shaped, 5-18 cm, in a ground-hugging basal rosette; 5-9 prominent parallel veins converging at base and tip; margins entire to slightly wavy; blade tapers into a channeled leaf stalk; hairless or only sparsely hairy.",
      stem: "No true leafy stem; leafless flowering stalks rise from the rosette center.",
      flowers: "Dense, narrow greenish spike of tiny inconspicuous flowers along the upper stalk.",
      fruit: "Small capsule splitting to release numerous tiny seeds.",
      root: "Short, fibrous root system.",
      aroma: "Mild, not aromatic.",
      height: "Rosette flat to the ground; flower stalks 5-40 cm.",
      keyFeatures: ["Flat basal rosette of broad leaves", "Prominent parallel veins that pull out as strings when a leaf is torn", "Leafless slender flower spikes", "Rounded, channeled leaf stalks"],
    },
    lookalikes: [
      { name: "Foxglove (first-year rosette)", scientific: "Digitalis purpurea", danger: "deadly", distinguishingFeature: "Its non-flowering rosette can look similar, but foxglove leaves are soft-HAIRY, gray-green and wrinkled with a NET (pinnate) vein pattern and finely toothed margins — versus plantain's hairless leaves with parallel veins and entire margins. If a rosette is hairy with net veins, do not pick — foxglove contains deadly cardiac glycosides.", keyFeatures: ["Soft-hairy, wrinkled gray-green leaves", "Net/pinnate venation", "Toothed leaf margins", "No parallel strings when torn"] },
      { name: "Narrowleaf/Ribwort Plantain", scientific: "Plantago lanceolata", danger: "edible", distinguishingFeature: "Narrow, lance-shaped leaves with parallel veins and a short bullet-like flower head; also edible and used the same way.", keyFeatures: ["Long narrow leaves", "Parallel veins", "Short dense flower head on a long stalk"] },
    ],
    culinary: { flavor: "Mild, slightly bitter and nutty; young leaves grassy and tender.", uses: "Young leaves raw in salads or cooked as a potherb; older leaves cooked with tough veins removed; seeds/husks as a psyllium-like thickener; leaves dried for tea.", preservation: "Dry leaves for tea; dry seeds for storage." },
    conservationNotes: "Non-native, cosmopolitan weed of disturbed and developed ground; no conservation concern. Because it grows in trampled, human-used areas, avoid sites likely sprayed with herbicide.",
    sources: [
      { name: "Wikipedia — Plantago major", url: "https://en.wikipedia.org/wiki/Plantago_major" },
      { name: "UC IPM Weed Gallery — Broadleaf Plantain", url: "https://ipm.ucanr.edu/PMG/WEEDS/broadleaf_plantain.html" },
      { name: "Practical Self Reliance — Plantain Herb", url: "https://practicalselfreliance.com/plantain-herb/" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "Broad agreement that plantain is a safe edible/medicinal green; note that P. major is largely absent from wildland high country but common in disturbed Tahoe-Truckee sites." },
  },
  {
    id: "red-clover",
    commonNames: ["Red Clover", "Purple Clover", "Meadow Clover"],
    scientific: "Trifolium pratense",
    family: "Fabaceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 20, max: 80 },
    habitat: "Roadsides, pastures, meadow edges, irrigated ground, and revegetated or seeded areas at foothill to montane elevations around Truckee and the Tahoe basin.",
    elevationM: { min: 300, max: 2500 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra", "Great Basin"],
    harvestMonths: [5, 6, 7, 8, 9],
    peakMonths: [6, 7, 8],
    seasonCue: { tempSensitive: false, notes: "Blooms over a long season once established; pick flower heads freshly opened and dry, before the florets brown, and young leaves before flowering." },
    edibleParts: ["flowers", "young-leaves", "leaves"],
    edibility: "edible",
    preparation: "Pick freshly opened flower heads and young pre-flowering leaves. Eat flowers raw as a garnish, dry them for tea, or grind dried heads into flour; use young leaves in small amounts raw or lightly cooked (cooking improves digestibility). Discard browned florets.",
    cautions: "Safe in food amounts. Large quantities of raw clover can cause bloating and GI upset — cook to improve digestibility. Flowers and leaves contain phytoestrogens and coumarins; medicinal or very large intake is best avoided in pregnancy, before surgery, or with blood-thinning medication. Never eat moldy or spoiled clover — fermentation can produce dicoumarol, an anticoagulant.",
    toxicityNotes: "Not toxic in normal food amounts; phytoestrogen and coumarin content warrant moderation at medicinal doses and caution for people who are pregnant or on anticoagulants.",
    identification: {
      leaves: "Alternate, trifoliate (three leaflets); each oval leaflet usually marked with a pale, V-shaped whitish 'chevron' watermark; finely toothed margins; bristle-tipped stipules at the leaf base.",
      stem: "Erect to ascending, branched, softly hairy.",
      flowers: "Dense globe- to egg-shaped heads of many small pink to reddish-purple tubular florets, sitting directly above a pair of leaves at the head's base.",
      fruit: "Tiny pod containing 1-2 seeds, enclosed in the persistent calyx.",
      root: "Taproot bearing nitrogen-fixing root nodules.",
      aroma: "Flowers faintly sweet and honey-like.",
      height: "20-80 cm.",
      keyFeatures: ["Three leaflets, each with a pale V-shaped chevron mark", "Pink-purple rounded flower heads seated on a pair of leaves", "Softly hairy stems", "Bristle-tipped stipules"],
    },
    lookalikes: [
      { name: "White Clover", scientific: "Trifolium repens", danger: "edible", distinguishingFeature: "White flower heads on leafless stalks and creeping stems; also edible with the same cautions.", keyFeatures: ["White globe flower heads", "Creeping stolons", "Flower stalk without a leaf pair beneath the head"] },
      { name: "Sweet Clover", scientific: "Melilotus officinalis", danger: "edible-with-caution", distinguishingFeature: "Trifoliate leaves too, but flowers are borne in long, slender ELONGATED spikes (not round heads); high in coumarin and dangerous if moldy — use sparingly and never spoiled.", keyFeatures: ["Long spike-like yellow or white flower clusters", "Sweet hay/coumarin smell when dried"] },
      { name: "Crown Vetch", scientific: "Securigera varia", danger: "toxic", distinguishingFeature: "Pinnately compound leaves with many (15-25) leaflets — NOT three — and pink-and-white crown-like flower clusters; contains toxic nitro-compounds, not for eating.", keyFeatures: ["Many small leaflets on a central stalk", "Crown of pink/white pea flowers", "Sprawling mats"] },
    ],
    culinary: { flavor: "Mildly sweet and beany; flowers faintly honey-sweet.", uses: "Flowers raw as a colorful garnish, dried for herbal tea, or ground into flour; young leaves raw in small amounts or cooked as greens.", preservation: "Air-dry flower heads for tea or flour; leaves best used fresh." },
    conservationNotes: "Non-native forage/cover crop, widely naturalized; no conservation concern. Avoid roadside plants exposed to spray or vehicle contamination.",
    sources: [
      { name: "Calflora — Trifolium pratense", url: "https://www.calflora.org/app/taxon?crn=8104" },
      { name: "Wikipedia — Trifolium pratense", url: "https://en.wikipedia.org/wiki/Trifolium_pratense" },
      { name: "Plants for a Future — Trifolium pratense", url: "https://pfaf.org/user/Plant.aspx?LatinName=Trifolium+pratense" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "Agreement that flowers and young leaves are edible; sources caution that large amounts of raw clover can cause bloating and that phytoestrogen/coumarin content warrants moderation." },
  },
  {
    id: "greenleaf-manzanita",
    commonNames: ["Greenleaf Manzanita", "Green Manzanita"],
    scientific: "Arctostaphylos patula",
    family: "Ericaceae",
    habit: "shrub",
    lifeCycle: "perennial",
    heightCm: { min: 100, max: 200 },
    habitat: "Open, sunny, well-drained decomposed-granite slopes, forest openings, montane chaparral, and burns within ponderosa/Jeffrey pine, red fir, and lodgepole forests; very common on the Tahoe rim and Truckee area, often among granite boulders.",
    elevationM: { min: 610, max: 3350 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra", "Great Basin"],
    harvestMonths: [6, 7, 8, 9, 10],
    peakMonths: [8, 9],
    seasonCue: { tempSensitive: true, notes: "Green berries for cider ripen early-mid summer; berries turn reddish-brown and mealy by late summer/fall. Fruiting staggers by elevation; timing shifts earlier in warm years." },
    edibleParts: ["berry", "flowers"],
    edibility: "edible",
    preparation: "Traditional 'manzanita cider': gather green-to-blushed or ripe berries, crush gently, steep in cold water, then strain out solids and hard seeds. For a tart fruit sugar/meal, dry the ripe berries and pulse briefly to pulverize only the soft flesh, then SIFT the powder off the hard seeds. Boiling in water breaks down the heavy tannins. Do not include twigs or leaves (intensely tannic).",
    cautions: "Berries are very high in tannins (astringent; excess can cause GI upset/constipation). Grind gently so the stony seeds stay intact — do not blend the seeds to a paste. Avoid using leaves/twigs.",
    toxicityNotes: "Flesh is non-toxic. The hard seeds contain cyanogenic compounds only released if the seeds are crushed/pulverized; swallowed whole they pass harmlessly. No deadly lookalikes, but high tannin content warrants moderation and proper preparation.",
    identification: {
      leaves: "Bright yellow-green, oval to nearly round, 2.5-6 cm, leathery, flat, smooth, held erect/vertically.",
      stem: "Crooked branches with characteristic smooth, shiny mahogany-red bark; mounding erect shrub, often forming a basal burl.",
      flowers: "White to pink, urn-shaped with 5 small lobes, 6-8 mm, hanging in dense drooping clusters; bloom April-June.",
      fruit: "Round drupe 6-10 mm, green ripening to reddish-brown, dry and mealy, each containing about 5 hard stony seeds.",
      root: "Woody burl/lignotuber at base.",
      aroma: "Faint; ripe berries mildly apple-tart.",
      height: "100-200 cm (occasionally to ~3 m), erect mounding shrub.",
      keyFeatures: ["Smooth mahogany-red bark", "Erect bright-green rounded leathery leaves", "Urn-shaped pink-white hanging flowers", "Dry, mealy round berries with hard stony seeds"],
    },
    lookalikes: [
      { name: "Other manzanitas (pinemat, whiteleaf)", scientific: "Arctostaphylos nevadensis, A. viscida", danger: "edible", distinguishingFeature: "All Arctostaphylos berries are edible and prepared the same way; pinemat manzanita is a low ground-hugging mat versus erect greenleaf. Not a safety concern.", keyFeatures: ["Smooth red bark", "Urn-shaped flowers", "Dry mealy berries"] },
      { name: "Toyon / Christmas berry", scientific: "Heteromeles arbutifolia", danger: "edible-with-caution", distinguishingFeature: "Toyon has toothed, elongate evergreen leaves and bright red pomes in large flat-topped clusters; raw fruit is cyanogenic and needs cooking. A foothill/chaparral species lacking manzanita's smooth red bark.", keyFeatures: ["Serrated lance-shaped leaves", "Clusters of small red pomes", "No smooth red bark"] },
    ],
    culinary: { flavor: "Tart and apple-like in green berries; ripe berries dry, mealy, mildly sweet-tart with strong astringency.", uses: "Manzanita cider/punch, tart fruit sugar/meal sifted from dried berries, jelly.", preservation: "Dry ripe berries and grind to powder; keep cider refrigerated." },
    conservationNotes: "Common and secure. Harvest berries lightly and leave plenty for bears and birds; avoid damaging these slow-growing, fire-adapted shrubs.",
    sources: [
      { name: "Calscape (CNPS): Greenleaf Manzanita", url: "https://calscape.org/Arctostaphylos-patula-(Greenleaf-Manzanita)" },
      { name: "USFS Fire Effects Information System (FEIS): Arctostaphylos patula", url: "https://www.fs.usda.gov/database/feis/plants/shrub/arcpat/all.html" },
      { name: "Hunter Angler Gardener Cook: How to Eat Manzanita Berries", url: "https://honest-food.net/manzanita-berries-edible/" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "All sources agree berries are edible (cider/meal). Only foraging sources flag that crushing the hard seeds can release cyanogenic compounds." },
  },
  {
    id: "dwarf-bilberry",
    commonNames: ["Dwarf Bilberry", "Dwarf Blueberry", "Dwarf Huckleberry", "Western Blue Huckleberry"],
    scientific: "Vaccinium cespitosum",
    family: "Ericaceae",
    habit: "shrub",
    lifeCycle: "perennial",
    heightCm: { min: 5, max: 50 },
    habitat: "Moist to wet subalpine and montane meadows, mossy conifer forest floors, streambanks, and gravelly slopes; forms low carpet-like mats. Documented in the Tahoe-Truckee area (Placer, Nevada, El Dorado counties).",
    elevationM: { min: 1800, max: 3660 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra"],
    harvestMonths: [8, 9],
    peakMonths: [8],
    seasonCue: { tempSensitive: true, notes: "Flowers June-July; berries ripen roughly August-early September. Ripening runs later at higher elevations and in cold years; harvest when berries are fully blue-black and come off easily." },
    edibleParts: ["berry"],
    edibility: "choice",
    preparation: "Eat ripe berries fresh, or use in pies, jam, syrup, pancakes; dry or freeze for storage. No special processing needed beyond washing. ONLY eat berries you have positively confirmed are Vaccinium.",
    cautions: "Primary risk is misidentification. Positively distinguish from toxic blue/black-berried plants before eating (see lookalikes). Confirm the tell-tale 5-pointed calyx 'crown' at the berry tip and whitish bloom.",
    toxicityNotes: "Berries are non-toxic. The danger is confusion with toxic lookalikes such as baneberry (deadly) and twinberry honeysuckle (inedible), not the bilberry itself.",
    identification: {
      leaves: "Bright green, thin, oval to elliptic (often widest above the middle), 1-3 cm, finely serrated margins, deciduous and turning red in fall.",
      stem: "Low, many-branched with greenish-to-reddish young twigs; spreads by rhizomes into low mats.",
      flowers: "Solitary (not clustered), pink to white, urn/bell-shaped, under 1 cm, nodding in leaf axils; bloom June-July.",
      fruit: "Round berry 4-8 mm, blue to blue-black with a pale waxy bloom, sweet, with many tiny seeds and a 5-pointed calyx ring at the tip.",
      root: "Shallow rhizomatous roots forming colonial mats.",
      aroma: "Berries mildly sweet, classic blueberry scent.",
      height: "5-30 cm (rarely to 50 cm), low mat-forming subshrub.",
      keyFeatures: ["Low carpet-forming subshrub of moist subalpine meadows", "Blue-black berry with whitish bloom and calyx 'crown' at the tip", "Solitary urn-shaped pink flowers", "Finely toothed deciduous leaves"],
    },
    lookalikes: [
      { name: "Red or white baneberry", scientific: "Actaea rubra", danger: "deadly", distinguishingFeature: "A tall leafy HERB (not a low woody mat) bearing a tight cluster of glossy red or white berries on a raceme; highly poisonous. Bilberry berries are dull blue-black with a whitish bloom and a calyx crown, borne singly on a low shrub.", catalogId: "red-baneberry", keyFeatures: ["Shiny red or white berries in a cluster", "Herbaceous plant", "Compound sharply toothed leaves"] },
      { name: "Twinberry honeysuckle", scientific: "Lonicera involucrata", danger: "inedible", distinguishingFeature: "Upright shrub bearing PAIRED shiny black berries cupped by conspicuous reddish-purple bracts; considered inedible/mildly toxic. Bilberry berries are solitary, dull-blue with bloom, and lack bracts.", keyFeatures: ["Berries in pairs", "Red-purple leafy bracts beneath berries", "Upright shrub, not a mat"] },
    ],
    culinary: { flavor: "Sweet, juicy, classic blueberry/huckleberry flavor; small but excellent.", uses: "Eaten fresh; pies, jam, syrup, pancakes, muffins.", preservation: "Freeze, dry, or make into jam/syrup." },
    conservationNotes: "Slow-growing subalpine mat species in fragile wet meadows and an important bear/wildlife food. Pick sparingly, avoid trampling saturated meadows, and leave ample fruit.",
    sources: [
      { name: "USFS Fire Effects Information System (FEIS): Vaccinium caespitosum", url: "https://www.fs.usda.gov/database/feis/plants/shrub/vaccae/all.html" },
      { name: "USFS Celebrating Wildflowers: Dwarf Bilberry", url: "https://www.fs.usda.gov/wildflowers/plant-of-the-week/vaccinium_cespitosum.shtml" },
      { name: "Calflora: Vaccinium cespitosum", url: "https://www.calflora.org/app/taxon?crn=8194" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "V. cespitosum (dwarf bilberry) selected as the widespread Tahoe-Truckee meadow species. All sources agree berries are edible; the calyx 'crown' is the key safety cue vs. toxic lookalikes." },
  },
  {
    id: "sierra-plum",
    commonNames: ["Sierra Plum", "Klamath Plum", "Pacific Plum"],
    scientific: "Prunus subcordata",
    family: "Rosaceae",
    habit: "shrub",
    lifeCycle: "perennial",
    heightCm: { min: 100, max: 800 },
    habitat: "Foothill and lower-montane slopes, canyon bottoms, riparian zones, chaparral edges, oak woodland, and yellow-pine forest; forms dense spiny root-suckering thickets. Most abundant on the west-slope Sierra foothills below the Tahoe basin, reaching the Truckee/Tahoe fringe.",
    elevationM: { min: 100, max: 1900 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee"],
    harvestMonths: [8, 9],
    peakMonths: [9],
    seasonCue: { tempSensitive: true, notes: "Blooms in early spring (roughly March-May) before/with the leaves; fruit ripens late summer (August-September). Ripe fruit is soft and comes away easily; unripe fruit is intensely tart." },
    edibleParts: ["fruit"],
    edibility: "edible",
    preparation: "Eat the FLESH of fully ripe fruit fresh, or cook into jam, jelly, preserves, pies, or fruit leather. Remove and discard the single stony pit before processing. Do NOT crush, grind, or eat the pit/kernel. Fully ripe fruit is far less tart than green fruit.",
    cautions: "Like all Prunus, the pit/seed contains cyanogenic glycosides (amygdalin). Never crush or eat the kernels; discard pits. Leaves, twigs, and wilted foliage are also cyanogenic — do not use them.",
    toxicityNotes: "Fruit flesh is edible and highly regarded. Seeds/pits, leaves, and bark contain cyanogenic glycosides that release hydrogen cyanide. Swallowing an intact pit is generally harmless, but crushing or chewing kernels is dangerous.",
    identification: {
      leaves: "Dark green, oval to nearly round, 2.5-6 cm, faintly/finely toothed, base often slightly heart-shaped (the source of 'subcordata'); deciduous, turning red in fall.",
      stem: "Erect, often crooked deciduous shrub or small tree with gray bark; branchlets stiff and somewhat spiny; forms dense thickets by root suckering.",
      flowers: "White aging pinkish, about 2 cm across, 5 petals, in clusters of 1-7, opening in early spring before or with the leaves.",
      fruit: "Oblong plum-like drupe 15-25 mm, red to yellow, often with a waxy bloom, tart to sweet-tart; a single large stony pit inside (discard).",
      root: "Suckering root system forming spiny thickets.",
      aroma: "Ripe fruit sweet-tart, plum-like.",
      height: "100-800 cm (commonly 1-6 m).",
      keyFeatures: ["Spiny, thicket-forming small tree/large shrub", "White 5-petaled flowers appearing before leaves", "Red or yellow plum 15-25 mm with one hard pit", "Subcordate, faintly toothed leaves"],
    },
    lookalikes: [
      { name: "Chokecherry", scientific: "Prunus virginiana var. demissa", danger: "edible-with-caution", distinguishingFeature: "Bears many small (6-10 mm) dark-purple cherries in elongated hanging RACEMES; flesh edible only cooked (astringent raw) and pits are cyanogenic. Sierra plum has larger (15-25 mm) single/few oblong plums.", catalogId: "western-chokecherry", keyFeatures: ["Berries in long clusters (racemes)", "Small round cherries", "Cyanogenic pits — never eat kernels"] },
    ],
    culinary: { flavor: "Tart to sweet-tart when fully ripe; regarded as one of the best-flavored wild fruits of the Pacific West.", uses: "Fresh eating when dead-ripe; jam, jelly, preserves, pies, fruit leather.", preservation: "Jam/jelly, canned, or dried with pits removed." },
    conservationNotes: "Locally common but patchy; thickets are valuable wildlife cover and food. Harvest fruit only and leave the root-suckering thickets intact.",
    sources: [
      { name: "Wikipedia: Prunus subcordata", url: "https://en.wikipedia.org/wiki/Prunus_subcordata" },
      { name: "Plants For A Future (PFAF): Prunus subcordata", url: "https://pfaf.org/user/Plant.aspx?LatinName=Prunus+subcordata" },
      { name: "Calscape (CNPS): Klamath/Sierra Plum", url: "https://calscape.org/Prunus-subcordata-(Klamath-Plum)" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "Strong agreement that the flesh is edible and highly regarded, and that (like all Prunus) the pit/kernel is cyanogenic and must not be eaten. Chiefly a west-slope foothill species reaching the Tahoe-Truckee fringe." },
  },
  {
    id: "whitebark-raspberry",
    commonNames: ["Whitebark Raspberry", "Blackcap Raspberry", "Blackcap", "Western Black Raspberry"],
    scientific: "Rubus leucodermis",
    family: "Rosaceae",
    habit: "shrub",
    lifeCycle: "perennial",
    heightCm: { min: 50, max: 250 },
    habitat: "Sunny forest openings, burns, clearcuts, roadsides, canyon slopes, and streambanks in yellow-pine, red-fir, and mixed-conifer forest; an early-successional shrub common in disturbed montane sites around Tahoe and Truckee.",
    elevationM: { min: 300, max: 2100 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range"],
    harvestMonths: [7, 8],
    peakMonths: [7, 8],
    seasonCue: { tempSensitive: true, notes: "Flowers roughly May-July; fruit ripens mid- to late summer (July-August), later at higher elevations. Berries are ripe when deep purple-black and pull off the receptacle leaving a hollow cap." },
    edibleParts: ["berry"],
    edibility: "choice",
    preparation: "Eat ripe berries fresh, or use in pies, jam, syrup, wine; dry or freeze for storage. No processing needed beyond washing; wear gloves/long sleeves against the prickly canes.",
    cautions: "Very safe. Avoid roadside or sprayed plants; watch the stout hooked prickles when picking. No toxic lookalikes among aggregate-berried Rubus.",
    toxicityNotes: "No toxic parts of the fruit. The aggregate-drupelet (raspberry-type) structure is a reliable safety feature — no toxic plant mimics it.",
    identification: {
      leaves: "Compound and pinnate: 5 leaflets on first-year canes, 3 on flowering branches; leaflets toothed, green above and conspicuously white-woolly beneath.",
      stem: "Arching biennial canes with a strong chalky blue-white waxy bloom over red bark, armed with stout hooked prickles.",
      flowers: "White (occasionally pale purple), 5 petals, in small terminal/axillary clusters; bloom May-July.",
      fruit: "Aggregate of many drupelets, 1-1.2 cm, red at first, ripening to dark purple-black; separates from the receptacle like a raspberry, leaving a hollow cap.",
      root: "Perennial woody crown; cane tips can root where they touch soil.",
      aroma: "Sweet raspberry aroma when ripe.",
      height: "50-250 cm.",
      keyFeatures: ["Chalky blue-white waxy canes with hooked prickles", "Leaves white-woolly beneath", "Berry pulls off hollow (raspberry-type), ripening black", "No toxic lookalikes among aggregate Rubus"],
    },
    lookalikes: [
      { name: "Thimbleberry", scientific: "Rubus parviflorus", danger: "edible", distinguishingFeature: "Large, soft, maple-shaped simple leaves and thornless stems; berry is a shallow, flat red cap. Fully edible.", catalogId: "thimbleberry", keyFeatures: ["Big fuzzy maple-shaped leaves", "Thornless stems", "Shallow red aggregate berry"] },
    ],
    culinary: { flavor: "Rich, sweet-tart, classic black-raspberry flavor; high in anthocyanins.", uses: "Fresh eating, pies, jam, syrup, wine, dried.", preservation: "Freeze, dry, or make into jam/syrup." },
    conservationNotes: "Common, fast-growing early-successional shrub; sustainable to harvest. Leave some fruit for birds and bears.",
    sources: [
      { name: "Wikipedia: Rubus leucodermis", url: "https://en.wikipedia.org/wiki/Rubus_leucodermis" },
      { name: "Calflora: Rubus leucodermis", url: "https://www.calflora.org/app/taxon?crn=7197" },
      { name: "Native Plants PNW: Blackcap Raspberry", url: "http://nativeplantspnw.com/blackcap-raspberry-rubus-leucodermis/" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "Unanimous that the fruit is edible and choice, with no toxic lookalikes among aggregate-berried Rubus." },
  },
  {
    id: "california-black-oak",
    commonNames: ["California Black Oak", "Kellogg Oak", "Black Oak"],
    scientific: "Quercus kelloggii",
    family: "Fagaceae",
    habit: "tree",
    lifeCycle: "perennial",
    heightCm: { min: 900, max: 3800 },
    habitat: "West-slope Sierra foothills to mid-montane forest: mixed-evergreen and mixed-conifer forest, oak woodland, and ponderosa/Jeffrey pine forest on well-drained slopes; reaches the lower/western Tahoe basin and the Truckee-area west slope.",
    elevationM: { min: 300, max: 2400 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee"],
    harvestMonths: [9, 10, 11],
    peakMonths: [10],
    seasonCue: { tempSensitive: false, notes: "Acorns ripen and drop in fall (September-November); acorns take two seasons to mature. The first acorns to fall are often insect-infested — collect the main October drop. Acorn abundance varies strongly year to year (masting)." },
    edibleParts: ["nut", "seeds"],
    edibility: "edible-cooked",
    preparation: "MANDATORY LEACHING. 1) Collect sound, fallen acorns in fall; float-test and discard floaters/holed nuts. 2) Dry, then shell off the hard outer shell and papery skin. 3) Grind the kernels into meal. 4) Leach out the bitter tannins: cold-leach in repeated changes of water (or a mesh bag in a stream) over hours-to-days until the water runs clear and the meal is no longer bitter, OR hot-leach with several changes of boiling water. 5) Cook the leached meal into mush, bread, or pancakes. Do NOT eat raw or unleached.",
    cautions: "Raw acorns are bitter, astringent, and high in tannins; leaching is required before eating. Do NOT confuse with toxic California buckeye seeds, which have NO scaly acorn cap. Discard moldy or insect-bored acorns.",
    toxicityNotes: "Raw acorns contain high levels of water-soluble tannins that cause GI distress and, in very large unleached quantities, can stress the kidneys. Tannins are removed by leaching; properly leached acorns are safe and nutritious.",
    identification: {
      leaves: "Large, 10-25 cm, deeply lobed into (5-)7 lobes with bristle-tipped teeth (red-oak group); glossy dark green above, paler below; orange-brown in fall; deciduous.",
      stem: "Trunk bark thin and smooth when young, becoming thick, deeply furrowed, and blackish in plates with age; broad rounded crown.",
      flowers: "Monoecious; yellow-green male catkins in spring; wind-pollinated.",
      fruit: "Acorn 2.5-4 cm, oblong, maturing over two seasons; a deep, thin, scaly cup encloses about a third to half of the nut; kernel bitter with tannins. Ripe September-November.",
      root: "Deep taproot; sprouts from the root crown after fire.",
      aroma: "Leached acorn meal is mild, nutty, faintly sweet.",
      height: "9-26 m, occasionally to ~38 m.",
      keyFeatures: ["Large 7-lobed, bristle-tipped leaves", "Blackish, deeply plated mature bark", "Acorn with a deep scaly cap covering roughly one-third of the nut", "Acorn takes two years to mature; bitter and requires leaching"],
    },
    lookalikes: [
      { name: "California buckeye (TOXIC — do not eat as a nut)", scientific: "Aesculus californica", danger: "toxic", distinguishingFeature: "Buckeye produces a single large 3-5 cm smooth, round, shiny brown seed with a big pale scar ('buck's-eye'), held in a leathery pear-shaped capsule — there is NO scaly acorn cap. Seeds contain toxic aesculin/saponins. Acorns instead have a scaly cup and pointed tip.", keyFeatures: ["Large smooth round seed with a pale scar", "No acorn cap", "Leathery pear-shaped husk"] },
    ],
    culinary: { flavor: "Mild, nutty, faintly sweet with a potato- or chestnut-like quality after leaching.", uses: "Ground into acorn flour/meal for mush, bread, and pancakes; a staple of California Indigenous cuisine and a preferred acorn for meal.", preservation: "Store thoroughly dried shelled acorns, or dry the leached meal/flour for keeping." },
    conservationNotes: "Keystone tree; acorns are a critical food for bears, deer, band-tailed pigeons, woodpeckers, and jays. Gather only fallen acorns, take a modest share, and never cut trees.",
    sources: [
      { name: "Wikipedia: Quercus kelloggii", url: "https://en.wikipedia.org/wiki/Quercus_kelloggii" },
      { name: "USDA NRCS Plant Guide: California black oak (Quercus kelloggii)", url: "https://plants.sc.egov.usda.gov/DocumentLibrary/plantguide/pdf/cs_quke.pdf" },
      { name: "Calscape (CNPS): Black Oak", url: "https://calscape.org/Quercus-kelloggii-(Black-Oak)" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "Unanimous that acorns are edible only after leaching tannins and were a Native Californian staple. Chiefly a west-slope species reaching the lower Tahoe/Truckee zone." },
  },
  {
    id: "red-baneberry",
    commonNames: ["Red Baneberry", "Baneberry", "Snakeberry", "Doll's-eyes (white-fruited form)"],
    scientific: "Actaea rubra",
    family: "Ranunculaceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 30, max: 100 },
    habitat: "Rich, moist, shaded ground in coniferous and mixed montane forest — streambanks, seep margins, shaded canyon bottoms, and north-facing slopes with deep leaf litter. A soft woodland herb of the same cool, damp forest where foragers hunt currants and other understory berries.",
    elevationM: { min: 1500, max: 3200 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra"],
    harvestMonths: [],
    peakMonths: [],
    seasonCue: { tempSensitive: false, notes: null },
    edibleParts: [],
    edibility: "deadly",
    preparation: "Do not consume any part. There is no preparation that makes baneberry safe.",
    cautions: "DEADLY. Every part is poisonous; the glossy berries and the root are the worst. Chewing releases protoanemonin, an intense irritant that causes near-immediate burning of the mouth and throat, salivation, severe nausea, vomiting, bloody diarrhea, dizziness and hallucinations. The berries also carry cardiogenic toxins that can slow or disturb the heartbeat and, in sufficient dose, cause cardiac arrest. As few as a handful of berries can be dangerous, especially to children, who are attracted to the bright, candy-like fruit. Onset is rapid (minutes to a couple of hours). If ingested, call Poison Control (1-800-222-1222) immediately.",
    toxicityNotes: "Contains ranunculin, which converts on tissue damage to protoanemonin (a blistering mucous-membrane irritant), plus cardiogenic compounds with a rapid disruptive effect on the heart. Toxins are present throughout the plant and concentrate in the berries and rootstock.",
    identification: {
      leaves: "Large, 2-3 times compound (each leaf divided into many leaflets); leaflets ovate, sharply and coarsely toothed and often lobed, thin and soft — herbaceous, never leathery. Only two or three big compound leaves per stem.",
      stem: "Erect, herbaceous (not woody), smooth, green, branched in the upper part; dies back to the ground each year.",
      flowers: "Small, white, in a short, dense, rounded terminal cluster with many fuzzy stamens; blooms late spring to early summer, before the berries form.",
      fruit: "A cluster of glossy, smooth berries carried erect on a stalk — typically bright cherry-red, sometimes porcelain-white — each berry tipped with a persistent dark stigma scar (a dark 'dot'). Ripens summer.",
      root: "Knotty, branching rhizome — highly toxic; never dig or taste.",
      aroma: "No distinctive smell; berries taste intensely bitter and acrid.",
      height: "About 30-100 cm (1-3 ft).",
      keyFeatures: ["Soft herb, NOT a woody shrub", "Large compound sharply-toothed leaflets (not lobed maple-like leaves)", "Glossy red (or white) berries in an erect terminal cluster on a stalk", "Each berry bears a dark stigma dot and has NO dried flower crown"],
    },
    lookalikes: [
      { name: "Currants & Gooseberries (Ribes)", scientific: "Ribes cereum, Ribes roezlii", danger: "edible", distinguishingFeature: "The edible Ribes it is confused with are WOODY shrubs with alternate, palmately lobed, maple-like leaves, and their berries keep a shriveled dried flower remnant ('crown') at the tip and hang from the branches (gooseberries are also spiny). Baneberry is a soft herb with big compound toothed leaves, and its glossy berries sit in an upright cluster on a stalk, each ending in a dark dot rather than a dried flower crown. If it is not woody and the berries lack the persistent flower crown, do not eat it.", catalogId: "currants-and-gooseberries", keyFeatures: ["Ribes = woody shrub with lobed maple-like leaves", "Ribes berry keeps a dried flower crown at the tip", "Ribes berries hang from branches", "Baneberry = herb, upright berry cluster, dark stigma dot"] },
    ],
    culinary: { flavor: "", uses: "Not edible — toxic.", preservation: null },
    conservationNotes: null,
    sources: [
      { name: "Calflora — Actaea rubra (Red Baneberry)", url: "https://www.calflora.org/app/taxon?crn=93" },
      { name: "Lady Bird Johnson Wildflower Center — Actaea rubra", url: "https://www.wildflower.org/plants/result.php?id_plant=acru2" },
      { name: "University of Wisconsin-Madison Horticulture Extension — Baneberry (Actaea spp.)", url: "https://hort.extension.wisc.edu/articles/baneberry-actaea-spp/" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "Sources agree all parts are poisonous and that berries carry cardiogenic toxins capable of cardiac arrest. Documented U.S. fatalities are scarce (the acrid taste deters large ingestion), so 'deadly' reflects the recognized cardiac hazard and severity." },
  },
  {
    id: "common-snowberry",
    commonNames: ["Common Snowberry", "Snowberry", "Waxberry", "Ghostberry"],
    scientific: "Symphoricarpos albus",
    family: "Caprifoliaceae",
    habit: "shrub",
    lifeCycle: "perennial",
    heightCm: { min: 60, max: 200 },
    habitat: "A very common understory and thicket-forming shrub of streambanks, canyon bottoms, moist woodland openings, forest edges and north-facing slopes throughout the montane Sierra and Tahoe basin; forms dense rhizomatous colonies. Its white berries persist on bare branches into fall and winter.",
    elevationM: { min: 1000, max: 2600 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra", "Great Basin"],
    harvestMonths: [],
    peakMonths: [],
    seasonCue: { tempSensitive: false, notes: null },
    edibleParts: [],
    edibility: "toxic",
    preparation: "Do not consume any part. The white berries are not food.",
    cautions: "TOXIC — do not eat. The waxy white berries look tempting and hang on through winter when little else is fruiting, so they are a common temptation for children and hikers. Eating them causes vomiting, diarrhea, abdominal cramps, dizziness and mild sedation; symptoms are usually mild-to-moderate and self-limiting, but the berries are consistently listed as poisonous and should never be eaten. Contact Poison Control (1-800-222-1222) if a child eats a quantity. Guiding rule: treat any wild white berry as inedible until proven otherwise.",
    toxicityNotes: "Berries contain saponins (which cause GI-tract irritation and are the main toxic principle) together with reported traces of isoquinoline alkaloids, plus other compounds. Saponins are poorly absorbed from the gut, which limits severity in humans, but the whole plant is regarded as poisonous.",
    identification: {
      leaves: "Opposite, oval to elliptic, mostly smooth-edged (entire) — sometimes wavy-lobed on vigorous shoots — dull gray-green, soft, 2-5 cm long.",
      stem: "Slender, woody, erect, thicket-forming; twigs finely hairy when young; no spines.",
      flowers: "Small (about 5 mm) pink to white, bell-shaped, in short clusters at the branch tips and leaf axils; bloom in summer.",
      fruit: "Round, waxy, pure-WHITE berry-like drupe about 1-1.5 cm across in tight clusters, with dry, spongy/mealy pulp and only two hard nutlets inside; persists on bare branches into winter.",
      root: "Spreading rhizomes forming colonies.",
      aroma: "No distinctive aroma; berry pulp dry and mealy, not juicy.",
      height: "Roughly 60-200 cm.",
      keyFeatures: ["Round, dry, waxy WHITE berry with only 2 hard seeds", "Opposite, smooth-edged leaves on a spineless woody shrub", "Berries in tight clusters at branch tips, persisting into winter", "Any wild white berry — treat as inedible"],
    },
    lookalikes: [
      { name: "Currants & Gooseberries (Ribes)", scientific: "Ribes spp.", danger: "edible", distinguishingFeature: "Edible currants and gooseberries produce JUICY, translucent berries packed with many tiny seeds, each keeping a shriveled dried flower remnant at the tip, on shrubs with alternate, palmately lobed maple-like leaves. Snowberry's white fruit is DRY and mealy with just two hard nutlets, in tight terminal clusters with no dried flower crown, on twigs with opposite, smooth-edged leaves.", catalogId: "currants-and-gooseberries", keyFeatures: ["Ribes = juicy, many-seeded, translucent berry with a dried flower crown", "Ribes leaves alternate & palmately lobed (maple-like)", "Snowberry = dry mealy white berry, 2 seeds, no crown", "Snowberry leaves opposite and smooth-edged"] },
    ],
    culinary: { flavor: "", uses: "Not edible — toxic.", preservation: null },
    conservationNotes: null,
    sources: [
      { name: "Calflora — Symphoricarpos albus (Common Snowberry)", url: "https://www.calflora.org/app/taxon?crn=10399" },
      { name: "USDA Forest Service FEIS — Symphoricarpos albus", url: "https://www.fs.usda.gov/database/feis/plants/shrub/symalb/all.html" },
      { name: "JAMA — Snowberry (Symphoricarpos) Poisoning in Children", url: "https://jamanetwork.com/journals/jama/fullarticle/367817" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "Sources agree the white berries are poisonous (saponin-driven GI irritation) and should not be eaten; human poisonings are usually mild with no well-documented fatalities, so 'toxic' rather than 'deadly'. The high-Tahoe form is often the equally toxic mountain snowberry (S. rotundifolius) — treat all Symphoricarpos berries the same." },
  },
  {
    id: "larkspur",
    commonNames: ["Larkspur", "Wild Larkspur", "Staggerweed", "Poisonweed"],
    scientific: "Delphinium spp.",
    family: "Ranunculaceae",
    habit: "herb",
    lifeCycle: "perennial",
    heightCm: { min: 20, max: 200 },
    habitat: "Open, sunny to lightly shaded ground: low larkspurs grow in sagebrush flats, grassy shrublands, open conifer forest and meadow edges on gravelly soil, while tall larkspurs grow in wet mountain meadows, seeps and streambanks. New basal leaves emerge with snowmelt, exactly when foragers gather early spring greens.",
    elevationM: { min: 1500, max: 3400 },
    regionsPNW: ["Sierra Nevada", "Tahoe", "Truckee", "Carson Range", "Eastern Sierra", "Great Basin"],
    harvestMonths: [],
    peakMonths: [],
    seasonCue: { tempSensitive: false, notes: null },
    edibleParts: [],
    edibility: "toxic",
    preparation: "Do not consume any part. No part of larkspur is edible at any stage.",
    cautions: "TOXIC — can be fatal. All parts are poisonous, with the young spring leaves and the seeds the most alkaloid-rich — exactly the tender rosette stage a forager might mistake for edible greens. Ingestion causes burning of the mouth and throat, nausea, vomiting, abdominal pain and diarrhea within hours, followed as the alkaloids are absorbed by muscle weakness and tremor, numbness, loss of coordination, a weak pulse, and — in serious cases — paralysis of the breathing muscles, convulsions and death. A California woman died after eating young larkspur she had gathered for a salad, mistaking it for wild mustard. Never eat unidentified spring greens; if ingested, call Poison Control (1-800-222-1222) at once.",
    toxicityNotes: "Contains numerous norditerpenoid alkaloids, chiefly the highly toxic methyllycaconitine (MLA), nudicauline and related compounds. These block muscle-type nicotinic acetylcholine receptors, producing neuromuscular paralysis; death is from respiratory failure. Alkaloid concentration is highest in the youngest growth and the seeds. Larkspurs kill more range cattle than any other poisonous plant, and human fatalities are documented.",
    identification: {
      leaves: "Palmately divided into deeply and narrowly cut, finger-like lobes (hand- or parsley-shaped), mostly basal and long-stalked early in the season; soft and green.",
      stem: "Erect; in the low larkspurs the stem is characteristically HOLLOW (a useful field check), while tall larkspurs are stout and up to ~2 m. Herbaceous.",
      flowers: "Showy, in an elongated terminal spike; each flower has 5 petal-like sepals, the uppermost drawn back into a long, straight, backward-pointing SPUR, usually deep blue to purple (occasionally white or pink).",
      fruit: "A cluster of dry, upright follicles that split to release many small seeds; seeds are especially toxic.",
      root: "A cluster of small fibrous or tuberous roots.",
      aroma: "No mustard/peppery or carrot smell — odorless foliage; the absence of a peppery smell helps rule out wild mustard.",
      height: "About 20-60 cm (low larkspurs) up to ~2 m (tall larkspurs).",
      keyFeatures: ["Palmately, deeply finger-cut leaves and NO peppery/mustard smell", "Flowers with a long backward-pointing SPUR (blue-purple)", "Low-larkspur stems are hollow", "Toxin peaks in the youngest spring leaves and seeds"],
    },
    lookalikes: [
      { name: "Wild mustard greens", scientific: "Brassica rapa / Hirschfeldia incana", danger: "edible", distinguishingFeature: "The edible spring green it is most dangerously confused with (a fatal California case involved larkspur gathered as 'wild mustard' for salad). Wild mustards have a distinct peppery/cabbage smell when crushed, lyre-shaped or toothed (not deeply finger-divided) leaves, and 4-petalled YELLOW cross-shaped flowers. Larkspur leaves are palmately cut into narrow fingers, have no peppery smell, and open into spurred blue-purple flowers. When in doubt, crush a leaf: no mustard smell means do not eat it.", keyFeatures: ["Mustard = peppery/cabbage smell + yellow 4-petal flowers", "Mustard leaves toothed/lyre-shaped, not finger-divided", "Larkspur = no smell, palmately cut narrow-lobed leaves", "Larkspur flowers are spurred and blue-purple"] },
      { name: "Western Monkshood", scientific: "Aconitum columbianum", danger: "deadly", distinguishingFeature: "A deadly relative with nearly identical palmately divided leaves that grows in the same wet Sierra meadows — routinely confused with larkspur, and BOTH are dangerously poisonous. Tell them apart by the flower: monkshood's top sepal forms an arched HELMET or hood, whereas larkspur's is drawn out into a long backward SPUR. Monkshood stems are solid; low-larkspur stems hollow. Neither is edible.", catalogId: "western-monkshood", keyFeatures: ["Monkshood flower = hooded helmet; larkspur flower = backward spur", "Monkshood stem solid; low larkspur stem hollow", "Both palmately divided leaves, both toxic", "Same wet-meadow / streambank habitat"] },
    ],
    culinary: { flavor: "", uses: "Not edible — toxic.", preservation: null },
    conservationNotes: null,
    sources: [
      { name: "Colorado State University — Guide to Poisonous Plants: Larkspur (Delphinium)", url: "https://poisonousplants.cvmbs.colostate.edu/plant/104" },
      { name: "Cornell University Poisonous Plants — Polycyclic Diterpene Alkaloids", url: "https://poisonousplants.ansci.cornell.edu/toxicagents/polycycl.html" },
      { name: "Calflora — Delphinium nuttallianum (Nuttall's Larkspur)", url: "https://www.calflora.org/app/taxon?crn=2656" },
    ],
    verification: { sourcesAgreeing: 4, consensus: "strong", disputeNotes: "Toxicology sources agree larkspurs carry potent norditerpenoid alkaloids that cause neuromuscular paralysis, that young growth and seeds are most toxic, and that they are lethal to livestock; documented human fatalities exist (a California salad case)." },
  },
];

export const GENERATED_PLANTS: PlantSpecies[] = SEED.map((p) => ({
  ...p,
  autoCompiled: true,
  verification: { ...p.verification, lastVerified: LAST_VERIFIED },
}));
